			{"ai_air_on"}
			{"arrows"}
			{"balance"}
			{"bot_army"}
			{"bot_difficulty"}
			{"bots_spawnside"}
			{"dcg_error"}
			{"dcg_on"}
			{"def_team"}
			{"display"}
			{"enemyid"}
			{"id_1st_enemy"}
			{"id_1st_player"}
			{"id_defenderbot"}
			{"music_hero"}
			{"music_intense"}
			{"music_rnd"}
			{"user_is_defender"}
			{"user_nation"}
			{"user_team"}
			{"tier2"}
			

;============ CE MECHANICS VARIABLES ========================================
			{"ai_sabotage"}			
			{"enable_ce_radio_mechanic"}
			{"radio_active"}
			{"enable_ce_cut_communications_mechanic"}
			{"enable_ai_abandon_mechanics"}
			{"human_wave_strategy_active"}
			{"punish_no_aa"}
			{"noresusenabled"}

;============ CE VARIABLES ========================================
			{"defense_level"}
			{"max_ai_defender_inf_per_flag_count"}
			{"max_ai_defender_emplacement_total_count"}
			{"max_ai_inf_def_x5_count"}
			{"max_ai_defender_inf_count"}
			{"current_ai_inf_def_x5_count"}
			{"enable_ai_waypoint_graphs"}
			{"max_ai_defender_emplacement_count_level_1"}
			{"max_ai_defender_emplacement_count_level_2"}
			{"max_ai_defender_emplacement_count_level_3"}
			{"ai_attack_started"}
			{"max_ai_defender_at_flag"}

;============ CE SPAWN VARIABLES			
			{"change_ai_spawns"}
			{"ai_spawn_strategy"}
			{"enable_rear_attack_mechanic"}	       