						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday1nowinter"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday2rain"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday3nowinter"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday4"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday5nowinter"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday6snow"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday7snow"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday8snow"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday9rain"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday10blizzard"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday11storm"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday12fog"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning1"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning2rain"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning3"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning4"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning5snow"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning6nowinter"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning7"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning8fog"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/evening1"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/evening2rain"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/evening3"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/evening4"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/evening5"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/evening6snow"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/evening7nowinter"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/night1"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/night2"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/night3"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/night4"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/night5"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/night6snow"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/night7"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/sunrise"}
								{time 8}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday4"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/spring/clear/evening_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/spring/clear/midday_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/spring/cloudy/morning_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/spring/cloudy/evening_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/spring/cloudy/midday_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/clear/morning_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/clear/evening_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/clear/midday_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/cloudy/morning_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/cloudy/midday_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/cloudy/midday_2"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/cloudy/midday_1b"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/cloudy/evening_1"}
								{time 8}
								{apply}
							}
						}
						{"default"
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/clear/midday_1b"}
								{time 8}
								{apply}
							}
						}{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/clear/morning_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/clear/evening_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/clear/midday_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/cloudy/morning_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/cloudy/midday_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/cloudy/midday_2"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/cloudy/midday_1b"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/autumn/cloudy/evening_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.13}
							}
							{"environment"
								{name "dynamic_campaign/autumn/clear/midday_1b"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/summer/clear/evening_01"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/summer/clear/midday_1"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/summer/cloudy/morning_01"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/summer/cloudy/evening_01"}
								{time 8}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/summer/cloudy/midday_1"}
								{time 8}
								{apply}
							}
						}						
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/summer/clear/morning_01"}
								{time 8}
								{apply}
							}
						}
						{"default"
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/spring/clear/morning_1"}
								{time 8}
								{apply}
							}
						}
                        