			{"environment/winter"
				{condition
				}
				{actions
					{"delay"
						{time 0.1}
					}
					{"switch"
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday2rain"}
								{time -1}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday4"}
								{time -1}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday6snow"}
								{time -1}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday7snow"}
								{time -1}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday8snow"}
								{time -1}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday9rain"}
								{time -1}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday10blizzard"}
								{time -1}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday11storm"}
								{time -1}
								{apply}
							}
						}
						{"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday12fog"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning1"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning2rain"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning3"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning4"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning5snow"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning7"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/morning8fog"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/evening1"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/evening2rain"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/evening3"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/evening4"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/evening5"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/evening6snow"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/night1"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/night2"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/night3"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/night4"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/night5"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/night6snow"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/night7"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.02}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/sunrise"}
								{time -1}
								{apply}
							}
						}
                        {"case"
							{condition
								{type rand}
								{value 0.3}
							}
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/mod/midday4"}
								{time -1}
								{apply}
							}
						}
                        {"default"
							{"delay"
								{time 0.1}
							}
							{"environment"
								{name "dynamic_campaign/winter/clear/morning_1"}
								{time -1}
								{apply}
							}
						}
					}
				}
			}