;============ Vanilla EVENTS ========================================
		
		{event "ai_air_on"}
		{event "ai_air_possible"}
		{event "airplane_set"}
		{event "dcg"}
		{event "dcg2/attack_bot_spawning"}
		{event "dcg2/defense_prep_end"}
		{event "dcg2/flags_set"}
		{event "flag1"}
		{event "flag2"}
		{event "flag3"}
		{event "flag4"}
		{event "flag5"}
		{event "init"}
		{event "init2"}
		{event "music_detect"}
		{event "music_intense"}
		{event "music_regular"}
		{event "music_reset"}
		{event "music_rnd"}
		{event "music_start"}
		{event "talk_on"}

;============ CE EVENTS ========================================

