; Vanilla var includes
(include "../multi/dcg_vars.inc")

;============ CE VARIABLES ========================================
	;{"enable_spawn_a_1_waypoint_grid"}
	;{"enable_spawn_a_2_waypoint_grid"}
	;{"enable_spawn_a_3_waypoint_grid"}
	;{"enable_spawn_a_4_waypoint_grid"}

	;{"enable_spawn_b_1_waypoint_grid"}
	;{"enable_spawn_b_2_waypoint_grid"}
	;{"enable_spawn_b_3_waypoint_grid"}
	;{"enable_spawn_b_4_waypoint_grid"}

	{"enable_waypoint_graph"}
	{"weather_selection"}
	{"season_set"}
	{"strong_weather_enabled"}

