{"ai_waypoint_pole"
	{on spawn 
		{tags add "drop_zone"}
	}
}


{"ai_waypoint_pole_side_a_row_1"
	{on spawn 
		{tags add "drop_zone"}
		{tags add "side_a_row_1"}
		{tags add "side_b_row_4"}
	}
}

{"ai_waypoint_pole_side_b_row_1"
	{on spawn 
		{tags add "drop_zone"}
		{tags add "side_b_row_1"}
		{tags add "side_a_row_4"}
	}
}

{"ai_waypoint_pole_side_a_row_2"
	{on spawn 
		{tags add "drop_zone"}
		{tags add "side_a_row_2"}
		{tags add "side_b_row_3"}
	}
}

{"ai_waypoint_pole_side_b_row_2"
	{on spawn 
		{tags add "drop_zone"}
		{tags add "side_b_row_2"}
		{tags add "side_a_row_3"}
	}
}

{"ai_waypoint_pole_side_a_row_3"
	{on spawn 
		{tags add "drop_zone"}
		{tags add "side_a_row_3"}
		{tags add "side_b_row_2"}
	}
}

{"ai_waypoint_pole_side_b_row_3"
	{on spawn 
		{tags add "drop_zone"}
		{tags add "side_b_row_3"}
		{tags add "side_a_row_2"}
	}
}

{"ai_waypoint_pole_side_a_row_4"
	{on spawn 
		{tags add "drop_zone"}
		{tags add "side_a_row_4"}
		{tags add "side_b_row_1"}
	}
}

{"ai_waypoint_pole_side_b_row_4"
	{on spawn 
		{tags add "drop_zone"}
		{tags add "side_b_row_4"}
		{tags add "side_a_row_1"}
	}
}
