;AUTOMATIC WEAPONRY
{"mg34_lafette"
	 {on spawn
	    {tags add "HMG"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
									        {tags add "enemymg"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"mg42_lafette"
	 {on spawn
	    {tags add "HMG"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
									        {tags add "enemymg"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"20mm_flak30"
	 {on spawn
	    {tags add "AAFLAK"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
									        {tags add "ai_aa"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"37mm_flak37"
	 {on spawn
	    {tags add "AAFLAK"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
									        {tags add "ai_aa"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}

; AT WEAPONRY
{"37mm_pak36"
	{on spawn
	    {tags add "at_gun"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
									        {tags add "ai_atgun"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"47mm_pakt"
	{on spawn
	    {tags add "at_gun"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
									        {tags add "ai_atgun"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"50mm_pak38"
	{on spawn
	    {tags add "at_gun"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_atgun"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"75mm_pak40"
	{on spawn
	    {tags add "at_gun"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
									        {tags add "ai_atgun"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"88mm_flak18"
	{on spawn
	    {tags add "at_gun"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_atgun"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"88mm_flak36"
	{on spawn
	    {tags add "at_gun"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_atgun"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}


;HOWITZERS
{"75mm_leig18"
	{on spawn
    	{tags add "artilllery"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "enemyarty"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"80mm_sgrw34"
	{on spawn
    	{tags add "artilllery"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "enemyarty"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"120mm_sgrw42"
	{on spawn
    	{tags add "artilllery"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								   {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "enemyarty"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"105mm_lefh18"
	{on spawn
    	{tags add "artilllery"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "enemyarty"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"150mm_nebelwerfer41"
	{on spawn
    	{tags add "artilllery"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_rocketarty"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"150mm_sig33"
	{on spawn
    	{tags add "artilllery"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "enemyarty"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"150mm_artillleryh18"
	{on spawn
    	{tags add "artilllery"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								   {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "enemyarty"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"210mm_morser18"
	{on spawn
    	{tags add "artilllery"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "enemyarty"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"300mm_nebelwerfer42"
	{on spawn
    	{tags add "artilllery"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_rocketarty"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}

;_________________________________________________
;|               Wheeled vehicles                 |
;|________________________________________________|

{"kubelwagen"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_car"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"kubelwagen_mg"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_car"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"blitz3_6"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_car"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"sdkfz10"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_car"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"sdkfz251c"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armoredcar"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"sdkfz221"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armoredcar"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"blitz3_6_flak30"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armoredcar"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"sdkfz231"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armoredcar"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"p204_f"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armoredcar"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"sdkfz234_2"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armoredcar"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"sdkfz10_pak38"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								   {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armoredcar"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"sdkfz8_flak18"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armoredcar"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"blitz3_6_art_ammo"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_car"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"blitz3_6_fuel"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_car"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"blitz3_6_engineering"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_car"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}

;_________________________________________________
;|        Main Battle Tanks and SPGs              |
;|________________________________________________|

;LIGHT
{"panzer1b"
	{on spawn
    	{tags add "light_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer1f"
	{on spawn
    	{tags add "light_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer2c"
	{on spawn
    	{tags add "light_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer2f"
	{on spawn
    	{tags add "light_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer2l"
	{on spawn
    	{tags add "light_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"pz35t"
	{on spawn
    	{tags add "light_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"pz38t_a"
	{on spawn
    	{tags add "light_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"pz38t_f"
	{on spawn
    	{tags add "light_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"pz38t_g"
	{on spawn
    	{tags add "light_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								   {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}

;MEDIUM
{"panzer3e"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer3f"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer3j"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer3j1"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer3l"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer3m"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer3n"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer3_flamm"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer4d"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer4f1"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer4f2"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer4g"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer4h"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer4j"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer5d"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer5a"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"panzer5g"
	{on spawn
    	{tags add "medium_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								   {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}

;HEAVY
{"tiger1h"
	{on spawn
    	{tags add "heavy_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"tiger1e"
	{on spawn
    	{tags add "heavy_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								   {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"tiger1hunt"
	{on spawn
    	{tags add "heavy_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"tiger2h"
	{on spawn
    	{tags add "heavy_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"tiger2p"
	{on spawn
    	{tags add "heavy_tank"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}

;SPG
{"panzerjager1"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"stug3b"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"marder2"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"marder3m"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"hetzer"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"grille_m"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"stug3f"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"stug3g"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"stug3g_late"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"stuh42"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"bison"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"sig33b"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"sturmpanzer4"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"ferdinand"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"jagdpanther"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}
{"sturmtiger"
	{on spawn
    	{tags add "spg"}
		{delay 6
		    {if not tagged "player_car"
			    {if not tagged "cmp_def"
			        {if not tagged "ger"
				        {if not tagged "rus"
					        {if not tagged "player_armor"
							    {if not tagged "player_veh"
								    {if not tagged "player"
									    {if not tagged "hidden"
										    {tags add "ai_armor"}
										}
									}
								}
						    }
					    }
				    }
			    }
		   }
	    }
	}
}

;_______________________________________________
;|					Aircraft					|
;|______________________________________________|

{"conquest_bf110"
	{on spawn
    	{tags add "aircraft"}
	}
}

{"bf110_e2" 
	{on spawn
    	{tags add "aircraft"}
	}
}
