	(include "entity_additons/extra_ai_defense_inf.inc")
	{Environment "goh/black"}
	{Helpers
		(include "conquest_enhanced_events.inc")
		{vars
			(include "conquest_enhanced_vars.inc")
		}
		{functions
			(include "conquest_enhanced_functions.inc")
		}
		{triggers
			(include "spring_environment.inc")
			(include "conquest_enhanced_triggers.inc")
		}
		(include "conquest_enhanced_generic_waypoint.inc")