	{Entity "spawn_point" 0x9002
		{Position -2535.68 -3195.05}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 1000}
	}
	{Entity "spawn_point" 0x9003
		{Position -2466.48 -3190.75}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3}
	}
	{Entity "spawn_point" 0x9004
		{Position -2536.58 -3128.8}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 4}
	}
	{Entity "spawn_point" 0x9005
		{Position -2471.44 -3128.37}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 5}
	}
	{Entity "spawn_point" 0x9006
		{Position -2687.06 -3124.79}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 6}
	}
	{Entity "spawn_point" 0x9007
		{Position -2691.13 -3182.95}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 7}
	}
	{Entity "spawn_point" 0x9008
		{Position -2761.93 -3135.92}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 8}
	}
	{Entity "spawn_point" 0x9009
		{Position -2764.96 -3177.93}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 9}
	}
	{Entity "spawn_point" 0x900a
		{Position -2592.82 -3547.55}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 10}
	}
	{Entity "spawn_point" 0x900b
		{Position -2512.35 -3548.45}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 11}
	}
	{Entity "spawn_point" 0x900c
		{Position -2582.45 -3486.5}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 12}
	}
	{Entity "spawn_point" 0x900d
		{Position -2519.28 -3495.55}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 13}
	}
	{Entity "spawn_point" 0x900e
		{Position -2732.93 -3482.49}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 14}
	}
	{Entity "spawn_point" 0x900f
		{Position -2737.01 -3540.65}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 15}
	}
	{Entity "spawn_point" 0x9010
		{Position -2807.8 -3493.62}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 16}
	}
	{Entity "spawn_point" 0x9011
		{Position -2810.83 -3535.63}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 17}
	}
	{Entity "spawn_point" 0x9012
		{Position -2602.56 -3906.4}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 18}
	}
	{Entity "spawn_point" 0x9013
		{Position -2531.43 -3907.8}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 19}
	}
	{Entity "spawn_point" 0x9014
		{Position -2601.53 -3845.85}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 20}
	}
	{Entity "spawn_point" 0x9015
		{Position -2534.1 -3845.47}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 21}
	}
	{Entity "spawn_point" 0x9016
		{Position -2752.01 -3841.84}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 22}
	}
	{Entity "spawn_point" 0x9017
		{Position -2756.09 -3900}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 23}
	}
	{Entity "spawn_point" 0x9018
		{Position -2826.88 -3852.97}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 24}
	}
	{Entity "spawn_point" 0x9019
		{Position -2829.91 -3894.98}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 25}
	}
	{Entity "spawn_point" 0x901a
		{Position -2076.82 -3624.74}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 26}
	}
	{Entity "spawn_point" 0x901b
		{Position -2002.63 -3625.78}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 27}
	}
	{Entity "spawn_point" 0x901c
		{Position -2072.73 -3563.83}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 28}
	}
	{Entity "spawn_point" 0x901d
		{Position -2004.9 -3556.05}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 29}
	}
	{Entity "spawn_point" 0x901e
		{Position -2223.21 -3559.82}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 30}
	}
	{Entity "spawn_point" 0x901f
		{Position -2227.29 -3617.98}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 31}
	}
	{Entity "spawn_point" 0x9020
		{Position -2298.08 -3570.95}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 32}
	}
	{Entity "spawn_point" 0x9021
		{Position -2301.11 -3612.96}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 33}
	}
	{Entity "spawn_point" 0x9022
		{Position -2062.71 -3367.96}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 34}
	}
	{Entity "spawn_point" 0x9023
		{Position -1990.59 -3370.25}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 35}
	}
	{Entity "spawn_point" 0x9024
		{Position -2060.69 -3308.3}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 36}
	}
	{Entity "spawn_point" 0x9025
		{Position -1996.43 -3306.44}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 37}
	}
	{Entity "spawn_point" 0x9026
		{Position -2211.17 -3304.29}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 38}
	}
	{Entity "spawn_point" 0x9027
		{Position -2215.25 -3362.45}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 39}
	}
	{Entity "spawn_point" 0x9028
		{Position -2286.04 -3315.42}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 40}
	}
	{Entity "spawn_point" 0x9029
		{Position -2289.07 -3357.43}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 41}
	}
	{Tags "5_a_1-3_mg" "5_b_1-3_mg" "cmp_def" 0x9002}
	{Tags "5_a_1-3_mg" "5_b_1-3_mg" "cmp_def" 0x9003}
	{Tags "5_b_1-3_mg" "5_a_1-3_mg" "cmp_def" 0x9004}
	{Tags "5_b_1-3_mg" "5_a_1-3_mg" "cmp_def" 0x9005}
	{Tags "5_b_1-3_mg" "5_a_1-3_mg" "cmp_def" 0x9006}
	{Tags "5_a_1-3_mg" "5_b_1-3_mg" "cmp_def" 0x9007}
	{Tags "5_b_1-3_mg" "5_a_1-3_mg" "cmp_def" 0x9008}
	{Tags "5_a_1-3_mg" "5_b_1-3_mg" "cmp_def" 0x9009}
	{Tags "4_b_1-3_mg" "4_a_1-3_mg" "cmp_def" 0x900a}
	{Tags "4_b_1-3_mg" "4_a_1-3_mg" "cmp_def" 0x900b}
	{Tags "4_a_1-3_mg" "4_b_1-3_mg" "cmp_def" 0x900c}
	{Tags "4_a_1-3_mg" "4_b_1-3_mg" "cmp_def" 0x900d}
	{Tags "4_a_1-3_mg" "4_b_1-3_mg" "cmp_def" 0x900e}
	{Tags "4_b_1-3_mg" "4_a_1-3_mg" "cmp_def" 0x900f}
	{Tags "4_a_1-3_mg" "4_b_1-3_mg" "cmp_def" 0x9010}
	{Tags "4_b_1-3_mg" "4_a_1-3_mg" "cmp_def" 0x9011}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9012}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9013}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9014}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9015}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9016}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9017}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9018}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9019}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x901a}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x901b}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x901c}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x901d}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x901e}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x901f}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x9020}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x9021}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9022}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9023}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9024}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9025}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9026}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9027}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9028}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9029}
