	{Entity "spawn_point" 0x9002
		{Position 226.86 2912.18}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 2}
	}
	{Entity "spawn_point" 0x9003
		{Position -733.18 5366.86}
		{xform zl -166.82}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3}
	}
	{Entity "spawn_point" 0x9004
		{Position -2068.55 3212.75}
		{xform zl 131.54}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 4}
	}
	{Entity "spawn_point" 0x9005
		{Position -593.36 4785.47}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 5}
	}
	{Entity "spawn_point" 0x9006
		{Position -1401.78 4211.09}
		{xform zl -157.8}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 6}
	}
	{Entity "spawn_point" 0x9007
		{Position 661.14 4594.98}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 7}
	}
	{Entity "spawn_point" 0x9008
		{Position 332.72 6828}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 8}
	}
	{Entity "spawn_point" 0x9009
		{Position -338.31 7247.75}
		{xform zl -151.01}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 9}
	}
	{Entity "spawn_point" 0x900a
		{Position -256.49 -276.86}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 10}
	}
	{Entity "spawn_point" 0x900b
		{Position 203.03 909.75}
		{xform zl 54.52}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 11}
	}
	{Entity "spawn_point" 0x900c
		{Position 300.1 1536.76}
		{xform zl 47.07}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 12}
	}
	{Entity "spawn_point" 0x900d
		{Position -1602.99 -1754.86}
		{xform zl -179.15}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 13}
	}
	{Entity "spawn_point" 0x900e
		{Position -1683.48 -741.42}
		{xform zl 166.37}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 14}
	}
	{Entity "spawn_point" 0x900f
		{Position -1068.22 -2119.43}
		{xform zl 154.34}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 15}
	}
	{Entity "spawn_point" 0x9010
		{Position -788.25 -2443.26}
		{xform zl -177.03}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 16}
	}
	{Entity "spawn_point" 0x9011
		{Position 882.13 -2162.74}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 17}
	}
	{Entity "spawn_point" 0x9012
		{Position -361.38 4454.02}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 18}
	}
	{Entity "spawn_point" 0x9013
		{Position -934.4 7071.3}
		{xform zl 171.06}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 19}
	}
	{Entity "spawn_point" 0x9014
		{Position -2476.37 4431.85}
		{xform zl -157.08}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 20}
	}
	{Entity "spawn_point" 0x9015
		{Position -1982.42 6355.18}
		{xform zl -172.96}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 21}
	}
	{Entity "spawn_point" 0x9016
		{Position -209.2 7076.6}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 22}
	}
	{Entity "spawn_point" 0x9017
		{Position 193.1 2251.36}
		{xform zl -47.62}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 23}
	}
	{Entity "spawn_point" 0x9018
		{Position 254.06 3606.2}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 24}
	}
	{Entity "spawn_point" 0x9019
		{Position -1076.19 4854.64}
		{xform zl 0.98}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 25}
	}
	{Entity "spawn_point" 0x901a
		{Position -2649.47 935.39}
		{xform zl -167.51}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 26}
	}
	{Entity "spawn_point" 0x901b
		{Position -1417.4 -2419.46}
		{xform zl -0.89}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 27}
	}
	{Entity "spawn_point" 0x901c
		{Position -2186.49 -657.31}
		{xform zl 139.38}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 28}
	}
	{Entity "spawn_point" 0x901d
		{Position -178.18 906.42}
		{xform zl 13.98}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 29}
	}
	{Entity "spawn_point" 0x901e
		{Position -2203.71 510.13}
		{xform zl 150.96}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 30}
	}
	{Entity "spawn_point" 0x901f
		{Position -1946.55 1898.81}
		{xform zl 114.85}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 31}
	}
	{Entity "spawn_point" 0x9020
		{Position -3414.75 -656.77}
		{xform zl -109.16}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 32}
	}
	{Entity "spawn_point" 0x9021
		{Position -2049.15 -2136.09}
		{xform zl 161.81}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 33}
	}
	{Entity "spawn_point" 0x9022
		{Position -2250.43 4065.68}
		{xform zl 130.75}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 34}
	}
	{Entity "spawn_point" 0x9023
		{Position -2314.01 2810.47}
		{xform zl 116.36}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 35}
	}
	{Entity "spawn_point" 0x9024
		{Position -2016.79 1105.64}
		{xform zl -143.29}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 36}
	}
	{Entity "spawn_point" 0x9025
		{Position -1626.34 3570.47}
		{xform zl 153.43}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 37}
	}
	{Entity "spawn_point" 0x9026
		{Position 197.08 3991.76}
		{xform zl 50.64}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 38}
	}
	{Entity "spawn_point" 0x9027
		{Position 225.47 3179.29}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 39}
	}
	{Entity "spawn_point" 0x9028
		{Position -189.87 1424.04}
		{xform zl 13.3}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 40}
	}
	{Entity "spawn_point" 0x9029
		{Position 222.29 92.68}
		{xform zl -52.16}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 41}
	}
	{Tags "5_a_1-3_mg" "5_b_1-3_mg" "cmp_def" 0x9002}
	{Tags "5_a_1-3_mg" "5_b_1-3_mg" "cmp_def" 0x9003}
	{Tags "5_a_1-3_mg" "5_b_1-3_mg" "cmp_def" 0x9004}
	{Tags "5_b_1-3_mg" "5_a_1-3_mg" "cmp_def" 0x9005}
	{Tags "5_b_1-3_mg" "5_a_1-3_mg" "cmp_def" 0x9006}
	{Tags "5_a_1-3_mg" "5_b_1-3_mg" "cmp_def" 0x9007}
	{Tags "5_b_1-3_mg" "5_a_1-3_mg" "cmp_def" 0x9008}
	{Tags "5_a_1-3_mg" "5_b_1-3_mg" "cmp_def" 0x9009}
	{Tags "4_b_1-3_mg" "4_a_1-3_mg" "cmp_def" 0x900a}
	{Tags "4_b_1-3_mg" "4_a_1-3_mg" "cmp_def" 0x900b}
	{Tags "4_a_1-3_mg" "4_b_1-3_mg" "cmp_def" 0x900c}
	{Tags "4_a_1-3_mg" "4_b_1-3_mg" "cmp_def" 0x900d}
	{Tags "4_a_1-3_mg" "4_b_1-3_mg" "cmp_def" 0x900e}
	{Tags "4_b_1-3_mg" "4_a_1-3_mg" "cmp_def" 0x900f}
	{Tags "4_a_1-3_mg" "4_b_1-3_mg" "cmp_def" 0x9010}
	{Tags "4_b_1-3_mg" "4_a_1-3_mg" "cmp_def" 0x9011}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9012}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9013}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9014}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9015}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9016}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9017}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9018}
	{Tags "3_a_1-3_mg" "3_b_1-3_mg" "cmp_def" 0x9019}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x901a}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x901b}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x901c}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x901d}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x901e}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x901f}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x9020}
	{Tags "2_a_1-3_mg" "2_b_1-3_mg" "cmp_def" 0x9021}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9022}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9023}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9024}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9025}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9026}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9027}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9028}
	{Tags "1_b_1-3_mg" "1_a_1-3_mg" "cmp_def" 0x9029}
