{Human "" 0x9100
		{Position 9013.08 2615.53 0.05}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 1}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9101
		{Position 9003.08 2605.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 2}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9102
		{Position 9003.08 2625.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 3}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9103
		{Position 9023.08 2605.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 4}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9104
		{Position 9023.08 2625.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 5}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9105
		{Position 8993.08 2595.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 6}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9106
		{Position 8993.08 2615.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 7}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9107
		{Position 9013.08 2595.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 8}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9108
		{Position 9033.08 2615.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 9}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9109
		{Position 8983.08 2605.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 10}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x910a
		{Position 8993.08 2635.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 11}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x910b
		{Position 9033.08 2595.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 12}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x910c
		{Position 9013.08 2635.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 13}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x910d
		{Position 8983.08 2585.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 14}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x910e
		{Position 8983.08 2625.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 15}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x910f
		{Position 9043.08 2605.53}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 16}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9165
		{Position 8995.02 2676.84}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 17}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9166
		{Position 9005.02 2666.84}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 18}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9167
		{Position 8985.02 2686.84}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 19}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9168
		{Position 9015.02 2656.84}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 20}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9169
		{Position 8989.33 2530.72}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 21}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x916a
		{Position 8999.33 2520.72}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 22}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x916b
		{Position 8979.33 2540.72}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 23}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x916c
		{Position 9009.33 2510.72}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 24}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x916d
		{Position 9822.12 2302.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 25}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9110
		{Position 9812.12 2292.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 26}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9111
		{Position 9812.12 2312.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 27}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9112
		{Position 9802.12 2282.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 28}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9113
		{Position 9832.12 2292.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 29}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9114
		{Position 9802.12 2302.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 30}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9115
		{Position 9832.12 2312.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 31}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9116
		{Position 9822.12 2282.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 32}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9117
		{Position 9842.12 2302.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 33}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9118
		{Position 9792.12 2292.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 34}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9119
		{Position 9802.12 2322.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 35}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x911a
		{Position 9792.12 2272.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 36}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x911b
		{Position 9822.12 2322.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 37}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x911c
		{Position 9792.12 2312.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 38}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x911d
		{Position 9842.12 2282.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 39}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x911e
		{Position 9812.12 2272.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 40}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x911f
		{Position 9842.12 2322.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 41}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9120
		{Position 9832.12 2272.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 42}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9121
		{Position 9852.12 2292.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 43}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9122
		{Position 9782.12 2282.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 44}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9123
		{Position 9852.12 2312.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 45}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9124
		{Position 9782.12 2302.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 46}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9125
		{Position 9792.12 2332.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 47}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9126
		{Position 9782.12 2262.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 48}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9127
		{Position 9812.12 2332.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 49}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9128
		{Position 9782.12 2322.68}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 50}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9129
		{Position 9064.05 1959.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 51}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x912a
		{Position 9054.05 1949.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 52}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x912b
		{Position 9054.05 1969.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 53}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x912c
		{Position 9044.05 1939.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 54}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x912d
		{Position 9074.05 1949.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 55}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x912e
		{Position 9044.05 1959.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 56}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x912f
		{Position 9074.05 1969.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 57}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9130
		{Position 9064.05 1939.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 58}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9131
		{Position 9084.05 1959.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 59}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9132
		{Position 9034.05 1949.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 60}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9133
		{Position 9044.05 1979.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 61}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9134
		{Position 9034.05 1929.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 62}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9135
		{Position 9064.05 1979.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 63}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9136
		{Position 9034.05 1969.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 64}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9137
		{Position 9084.05 1939.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 65}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9138
		{Position 9054.05 1929.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 66}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9139
		{Position 9084.05 1979.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 67}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x913a
		{Position 9074.05 1929.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 68}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x913b
		{Position 9094.05 1949.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 69}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x913c
		{Position 9024.05 1939.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 70}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x913d
		{Position 9094.05 1969.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 71}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x913e
		{Position 9024.05 1959.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 72}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x913f
		{Position 9034.05 1989.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 73}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9140
		{Position 9024.05 1919.87}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 74}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9141
		{Position 9880.82 1796.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 75}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9142
		{Position 9870.82 1786.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 76}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9143
		{Position 9870.82 1806.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 77}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9144
		{Position 9860.82 1776.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 78}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9145
		{Position 9890.82 1786.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 79}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9146
		{Position 9860.82 1796.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 80}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9147
		{Position 9890.82 1806.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 81}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9148
		{Position 9880.82 1776.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 82}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9149
		{Position 9900.82 1796.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 83}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x914a
		{Position 9850.82 1786.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 84}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x914b
		{Position 9860.82 1816.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 85}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x914c
		{Position 9850.82 1766.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 86}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x914d
		{Position 9880.82 1816.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 87}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x914e
		{Position 9850.82 1806.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 88}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x914f
		{Position 9900.82 1776.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 89}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9150
		{Position 9870.82 1766.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 90}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9151
		{Position 9900.82 1816.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 91}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9152
		{Position 9890.82 1766.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 92}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9153
		{Position 9910.82 1786.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 93}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9154
		{Position 9840.82 1776.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 94}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9155
		{Position 9910.82 1806.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 95}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9156
		{Position 9840.82 1796.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 96}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9157
		{Position 9850.82 1826.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 97}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9158
		{Position 9840.82 1756.66}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 98}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9159
		{Position 9938.2 1372.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 99}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x915a
		{Position 9928.2 1362.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 100}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x915b
		{Position 9928.2 1382.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 101}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x915c
		{Position 9918.2 1352.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 102}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x915d
		{Position 9948.2 1362.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 103}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x915e
		{Position 9918.2 1372.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 104}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x915f
		{Position 9948.2 1382.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 105}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9160
		{Position 9938.2 1352.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 106}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9161
		{Position 9958.2 1372.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 107}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9162
		{Position 9908.2 1362.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 108}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9163
		{Position 9918.2 1392.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 109}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9164
		{Position 9908.2 1342.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 110}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x916e
		{Position 9938.2 1392.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 111}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x916f
		{Position 9908.2 1382.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 112}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9170
		{Position 9958.2 1352.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 113}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9171
		{Position 9928.2 1342.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 114}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9172
		{Position 9958.2 1392.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 115}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9173
		{Position 9948.2 1342.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 116}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9174
		{Position 9968.2 1362.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 117}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9175
		{Position 9898.2 1352.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 118}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9176
		{Position 9968.2 1382.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 119}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9177
		{Position 9898.2 1372.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 120}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9178
		{Position 9908.2 1402.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 121}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x9179
		{Position 9898.2 1332.69}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 122}
		{FsmState "stand_noaim"}
	}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x9100}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x9101}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x9102}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x9103}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x9104}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x9105}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x9106}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x9107}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x9108}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x9109}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x910a}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x910b}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x910c}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x910d}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x910e}
	{Tags "cmp_def" "1_a_1-3" "1_b_1-3" 0x910f}
	{Tags "cmp_def" "1_b_1-3" "1_a_1-3" 0x9165}
	{Tags "cmp_def" "1_b_1-3" "1_a_1-3" 0x9166}
	{Tags "cmp_def" "1_b_1-3" "1_a_1-3" 0x9167}
	{Tags "cmp_def" "1_b_1-3" "1_a_1-3" 0x9168}
	{Tags "cmp_def" "1_b_1-3" "1_a_1-3" 0x9169}
	{Tags "cmp_def" "1_b_1-3" "1_a_1-3" 0x916a}
	{Tags "cmp_def" "1_b_1-3" "1_a_1-3" 0x916b}
	{Tags "cmp_def" "1_b_1-3" "1_a_1-3" 0x916c}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x916d}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9110}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9111}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9112}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9113}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9114}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9115}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9116}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9117}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9118}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9119}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x911a}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x911b}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x911c}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x911d}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x911e}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x911f}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9120}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9121}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9122}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9123}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9124}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9125}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9126}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9127}
	{Tags "cmp_def" "2_a_1-3" "2_b_1-3" 0x9128}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x9129}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x912a}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x912b}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x912c}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x912d}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x912e}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x912f}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x9130}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x9131}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x9132}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x9133}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x9134}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x9135}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x9136}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x9137}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x9138}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x9139}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x913a}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x913b}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x913c}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x913d}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x913e}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x913f}
	{Tags "cmp_def" "3_a_1-3" "3_b_1-3" 0x9140}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9141}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9142}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9143}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9144}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9145}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9146}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9147}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9148}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9149}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x914a}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x914b}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x914c}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x914d}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x914e}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x914f}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9150}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9151}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9152}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9153}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9154}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9155}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9156}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9157}
	{Tags "cmp_def" "4_a_1-3" "4_b_1-3" 0x9158}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9159}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x915a}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x915b}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x915c}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x915d}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x915e}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x915f}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9160}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9161}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9162}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9163}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9164}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x916e}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x916f}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9170}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9171}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9172}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9173}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9174}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9175}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9176}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9177}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9178}
	{Tags "cmp_def" "5_a_1-3" "5_b_1-3" 0x9179}
	{Inventory 0x9100
		{box
			{clear}
		}
	}
	{Inventory 0x9101
		{box
			{clear}
		}
	}
	{Inventory 0x9102
		{box
			{clear}
		}
	}
	{Inventory 0x9103
		{box
			{clear}
		}
	}
	{Inventory 0x9104
		{box
			{clear}
		}
	}
	{Inventory 0x9105
		{box
			{clear}
		}
	}
	{Inventory 0x9106
		{box
			{clear}
		}
	}
	{Inventory 0x9107
		{box
			{clear}
		}
	}
	{Inventory 0x9108
		{box
			{clear}
		}
	}
	{Inventory 0x9109
		{box
			{clear}
		}
	}
	{Inventory 0x910a
		{box
			{clear}
		}
	}
	{Inventory 0x910b
		{box
			{clear}
		}
	}
	{Inventory 0x910c
		{box
			{clear}
		}
	}
	{Inventory 0x910d
		{box
			{clear}
		}
	}
	{Inventory 0x910e
		{box
			{clear}
		}
	}
	{Inventory 0x910f
		{box
			{clear}
		}
	}
	{Inventory 0x9165
		{box
			{clear}
		}
	}
	{Inventory 0x9166
		{box
			{clear}
		}
	}
	{Inventory 0x9167
		{box
			{clear}
		}
	}
	{Inventory 0x9168
		{box
			{clear}
		}
	}
	{Inventory 0x9169
		{box
			{clear}
		}
	}
	{Inventory 0x916a
		{box
			{clear}
		}
	}
	{Inventory 0x916b
		{box
			{clear}
		}
	}
	{Inventory 0x916c
		{box
			{clear}
		}
	}
	{Inventory 0x916d
		{box
			{clear}
		}
	}
	{Inventory 0x9110
		{box
			{clear}
		}
	}
	{Inventory 0x9111
		{box
			{clear}
		}
	}
	{Inventory 0x9112
		{box
			{clear}
		}
	}
	{Inventory 0x9113
		{box
			{clear}
		}
	}
	{Inventory 0x9114
		{box
			{clear}
		}
	}
	{Inventory 0x9115
		{box
			{clear}
		}
	}
	{Inventory 0x9116
		{box
			{clear}
		}
	}
	{Inventory 0x9117
		{box
			{clear}
		}
	}
	{Inventory 0x9118
		{box
			{clear}
		}
	}
	{Inventory 0x9119
		{box
			{clear}
		}
	}
	{Inventory 0x911a
		{box
			{clear}
		}
	}
	{Inventory 0x911b
		{box
			{clear}
		}
	}
	{Inventory 0x911c
		{box
			{clear}
		}
	}
	{Inventory 0x911d
		{box
			{clear}
		}
	}
	{Inventory 0x911e
		{box
			{clear}
		}
	}
	{Inventory 0x911f
		{box
			{clear}
		}
	}
	{Inventory 0x9120
		{box
			{clear}
		}
	}
	{Inventory 0x9121
		{box
			{clear}
		}
	}
	{Inventory 0x9122
		{box
			{clear}
		}
	}
	{Inventory 0x9123
		{box
			{clear}
		}
	}
	{Inventory 0x9124
		{box
			{clear}
		}
	}
	{Inventory 0x9125
		{box
			{clear}
		}
	}
	{Inventory 0x9126
		{box
			{clear}
		}
	}
	{Inventory 0x9127
		{box
			{clear}
		}
	}
	{Inventory 0x9128
		{box
			{clear}
		}
	}
	{Inventory 0x9129
		{box
			{clear}
		}
	}
	{Inventory 0x912a
		{box
			{clear}
		}
	}
	{Inventory 0x912b
		{box
			{clear}
		}
	}
	{Inventory 0x912c
		{box
			{clear}
		}
	}
	{Inventory 0x912d
		{box
			{clear}
		}
	}
	{Inventory 0x912e
		{box
			{clear}
		}
	}
	{Inventory 0x912f
		{box
			{clear}
		}
	}
	{Inventory 0x9130
		{box
			{clear}
		}
	}
	{Inventory 0x9131
		{box
			{clear}
		}
	}
	{Inventory 0x9132
		{box
			{clear}
		}
	}
	{Inventory 0x9133
		{box
			{clear}
		}
	}
	{Inventory 0x9134
		{box
			{clear}
		}
	}
	{Inventory 0x9135
		{box
			{clear}
		}
	}
	{Inventory 0x9136
		{box
			{clear}
		}
	}
	{Inventory 0x9137
		{box
			{clear}
		}
	}
	{Inventory 0x9138
		{box
			{clear}
		}
	}
	{Inventory 0x9139
		{box
			{clear}
		}
	}
	{Inventory 0x913a
		{box
			{clear}
		}
	}
	{Inventory 0x913b
		{box
			{clear}
		}
	}
	{Inventory 0x913c
		{box
			{clear}
		}
	}
	{Inventory 0x913d
		{box
			{clear}
		}
	}
	{Inventory 0x913e
		{box
			{clear}
		}
	}
	{Inventory 0x913f
		{box
			{clear}
		}
	}
	{Inventory 0x9140
		{box
			{clear}
		}
	}
	{Inventory 0x9141
		{box
			{clear}
		}
	}
	{Inventory 0x9142
		{box
			{clear}
		}
	}
	{Inventory 0x9143
		{box
			{clear}
		}
	}
	{Inventory 0x9144
		{box
			{clear}
		}
	}
	{Inventory 0x9145
		{box
			{clear}
		}
	}
	{Inventory 0x9146
		{box
			{clear}
		}
	}
	{Inventory 0x9147
		{box
			{clear}
		}
	}
	{Inventory 0x9148
		{box
			{clear}
		}
	}
	{Inventory 0x9149
		{box
			{clear}
		}
	}
	{Inventory 0x914a
		{box
			{clear}
		}
	}
	{Inventory 0x914b
		{box
			{clear}
		}
	}
	{Inventory 0x914c
		{box
			{clear}
		}
	}
	{Inventory 0x914d
		{box
			{clear}
		}
	}
	{Inventory 0x914e
		{box
			{clear}
		}
	}
	{Inventory 0x914f
		{box
			{clear}
		}
	}
	{Inventory 0x9150
		{box
			{clear}
		}
	}
	{Inventory 0x9151
		{box
			{clear}
		}
	}
	{Inventory 0x9152
		{box
			{clear}
		}
	}
	{Inventory 0x9153
		{box
			{clear}
		}
	}
	{Inventory 0x9154
		{box
			{clear}
		}
	}
	{Inventory 0x9155
		{box
			{clear}
		}
	}
	{Inventory 0x9156
		{box
			{clear}
		}
	}
	{Inventory 0x9157
		{box
			{clear}
		}
	}
	{Inventory 0x9158
		{box
			{clear}
		}
	}
	{Inventory 0x9159
		{box
			{clear}
		}
	}
	{Inventory 0x915a
		{box
			{clear}
		}
	}
	{Inventory 0x915b
		{box
			{clear}
		}
	}
	{Inventory 0x915c
		{box
			{clear}
		}
	}
	{Inventory 0x915d
		{box
			{clear}
		}
	}
	{Inventory 0x915e
		{box
			{clear}
		}
	}
	{Inventory 0x915f
		{box
			{clear}
		}
	}
	{Inventory 0x9160
		{box
			{clear}
		}
	}
	{Inventory 0x9161
		{box
			{clear}
		}
	}
	{Inventory 0x9162
		{box
			{clear}
		}
	}
	{Inventory 0x9163
		{box
			{clear}
		}
	}
	{Inventory 0x9164
		{box
			{clear}
		}
	}
	{Inventory 0x916e
		{box
			{clear}
		}
	}
	{Inventory 0x916f
		{box
			{clear}
		}
	}
	{Inventory 0x9170
		{box
			{clear}
		}
	}
	{Inventory 0x9171
		{box
			{clear}
		}
	}
	{Inventory 0x9172
		{box
			{clear}
		}
	}
	{Inventory 0x9173
		{box
			{clear}
		}
	}
	{Inventory 0x9174
		{box
			{clear}
		}
	}
	{Inventory 0x9175
		{box
			{clear}
		}
	}
	{Inventory 0x9176
		{box
			{clear}
		}
	}
	{Inventory 0x9177
		{box
			{clear}
		}
	}
	{Inventory 0x9178
		{box
			{clear}
		}
	}
	{Inventory 0x9179
		{box
			{clear}
		}
	}
	{Brain 0x9100
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9101
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9102
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9103
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9104
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9105
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9106
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9107
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9108
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9109
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x910a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x910b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x910c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x910d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x910e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x910f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9165
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9166
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9167
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9168
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9169
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x916a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x916b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x916c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x916d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9110
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9111
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9112
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9113
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9114
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9115
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9116
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9117
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9118
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9119
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x911a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x911b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x911c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x911d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x911e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x911f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9120
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9121
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9122
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9123
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9124
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9125
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9126
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9127
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9128
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9129
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x912a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x912b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x912c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x912d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x912e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x912f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9130
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9131
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9132
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9133
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9134
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9135
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9136
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9137
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9138
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9139
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x913a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x913b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x913c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x913d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x913e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x913f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9140
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9141
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9142
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9143
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9144
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9145
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9146
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9147
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9148
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9149
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x914a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x914b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x914c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x914d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x914e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x914f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9150
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9151
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9152
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9153
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9154
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9155
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9156
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9157
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9158
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9159
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x915a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x915b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x915c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x915d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x915e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x915f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9160
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9161
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9162
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9163
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9164
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x916e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x916f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9170
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9171
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9172
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9173
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9174
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9175
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9176
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9177
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9178
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x9179
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}