{Entity "spawn_point" 0x9002
		{Position 1500 -525}
		{xform zl -10}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3957}
	}
	{Entity "spawn_point" 0x9003
		{Position 105 585}
		{xform zl 90}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3958}
	}
	{Entity "spawn_point" 0x9004
		{Position 1570 605}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3959}
	}
	{Entity "spawn_point" 0x9005
		{Position 150 260}
		{xform zl 130}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3960}
	}
	{Entity "spawn_point" 0x9006
		{Position 3330 -3250}
		{xform zl 10}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3961}
	}
	{Entity "spawn_point" 0x9007
		{Position 2705 -4875}
		{xform zl -140}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3962}
	}
	{Entity "spawn_point" 0x9008
		{Position 3070 -2850}
		{xform zl 50}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3963}
	}
	{Entity "spawn_point" 0x9009
		{Position 1890 -3800}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3964}
	}
	{Entity "spawn_point" 0x900a
		{Position -605 6295}
		{xform zl 140}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3965}
	}
	{Entity "spawn_point" 0x900b
		{Position 775 5515}
		{xform zl 50}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3966}
	}
	{Entity "spawn_point" 0x900c
		{Position -1100 5640}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3967}
	}
	{Entity "spawn_point" 0x900d
		{Position -930 4210}
		{xform zl -100}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3968}
	}
	{Entity "spawn_point" 0x900e
		{Position 7680 -4075}
		{xform zl 100}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3969}
	}
	{Entity "spawn_point" 0x900f
		{Position 6365 -4015}
		{xform zl 130}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3970}
	}
	{Entity "spawn_point" 0x9010
		{Position 5420 -3685}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3971}
	}
	{Entity "spawn_point" 0x9011
		{Position 5525 -6315}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3972}
	}
	{Entity "spawn_point" 0x9012
		{Position -5390 1420}
		{xform zl -90}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3973}
	}
	{Entity "spawn_point" 0x9013
		{Position -7140 2490}
		{xform zl -100}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3974}
	}
	{Entity "spawn_point" 0x9014
		{Position -5190 3870}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3975}
	}
	{Entity "spawn_point" 0x9015
		{Position -6390 3390}
		{xform zl 30}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3976}
	}
	{Entity "spawn_point" 0x9016
		{Position 368.26 -721.15}
		{xform zl -139.08}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 273}
	}
	{Entity "spawn_point" 0x9017
		{Position 3625.06 -2729}
		{xform zl -145.38}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 275}
	}
	{Entity "spawn_point" 0x9018
		{Position -484.5 4318.71}
		{xform zl -105.33}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 293}
	}
	{Entity "spawn_point" 0x9019
		{Position 6048.51 -3382.49}
		{xform zl -135.44}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 295}
	}
	{Entity "spawn_point" 0x901a
		{Position -4478.08 206.76}
		{xform zl -159.62}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 313}
	}
	{Entity "spawn_point" 0x901b
		{Position -288.17 5261.34}
		{xform zl -151.8}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 214}
	}
	{Entity "spawn_point" 0x901c
		{Position 1067.3 -683.82}
		{xform zl -91.61}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 215}
	}
	{Entity "spawn_point" 0x901d
		{Position -5543.32 1532.97}
		{xform zl -77.18}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 216}
	}
	{Entity "spawn_point" 0x901e
		{Position 2219.27 -4173.47}
		{xform zl -167.74}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 217}
	}
	{Entity "spawn_point" 0x901f
		{Position 5803.49 -5928.76}
		{xform zl 179.02}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 220}
	}
	{Entity "spawn_point" 0x9020
		{Position 6417.21 -3468.41}
		{xform zl 73.75}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 768}
	}
	{Entity "spawn_point" 0x9022
		{Position 8137.49 -5784.39}
		{xform zl 73.75}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 769}
	}
	{Entity "spawn_point" 0x9023
		{Position 4273.63 -5659.03}
		{xform zl -152.73}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 770}
	}
	{Entity "spawn_point" 0x9026
		{Position 5723.45 -3896.66}
		{xform zl 150.25}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 771}
	}
	{Entity "spawn_point" 0x9027
		{Position 5124.02 -3027.31}
		{xform zl 178.41}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 772}
	}
	{Entity "spawn_point" 0x902a
		{Position 4094.62 -5537.26}
		{xform zl 178.41}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 773}
	}
	{Entity "spawn_point" 0x902c
		{Position 5058.52 -2753.49}
		{xform zl 76.83}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 774}
	}
	{Entity "spawn_point" 0x9030
		{Position 5623.9 -2814.57}
		{xform zl 84.73}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 775}
	}
	{Entity "spawn_point" 0x9031
		{Position 2969.06 -1752.93}
		{xform zl 57.5}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 776}
	}
	{Entity "spawn_point" 0x9033
		{Position 2797.66 -2439.59}
		{xform zl 60.77}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 777}
	}
	{Entity "spawn_point" 0x9034
		{Position 2864 -5038.84}
		{xform zl -167.74}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 778}
	}
	{Entity "spawn_point" 0x9036
		{Position 2557.76 -4524.42}
		{xform zl -167.74}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 779}
	}
	{Entity "spawn_point" 0x9037
		{Position 1822.54 -2725.83}
		{xform zl 160}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 780}
	}
	{Entity "spawn_point" 0x903a
		{Position 1116.86 -2337.87}
		{xform zl -129.61}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 781}
	}
	{Entity "spawn_point" 0x903b
		{Position 4033.2 -2121.03}
		{xform zl 57.5}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 782}
	}
	{Entity "spawn_point" 0x903d
		{Position 3355.28 -665.18}
		{xform zl 57.5}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 783}
	}
	{Entity "spawn_point" 0x9041
		{Position 1667.24 88.8}
		{xform zl 23.32}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 784}
	}
	{Entity "spawn_point" 0x9043
		{Position 2068.74 -529.3}
		{xform zl 39.15}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 785}
	}
	{Entity "spawn_point" 0x9044
		{Position 37.72 -190.06}
		{xform zl -137.72}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 786}
	}
	{Entity "spawn_point" 0x9046
		{Position 540.03 -1489.54}
		{xform zl -123.13}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 787}
	}
	{Entity "spawn_point" 0x9047
		{Position 227.95 -2036.42}
		{xform zl -147.89}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 788}
	}
	{Entity "spawn_point" 0x904f
		{Position -1128.8 95.02}
		{xform zl -147.89}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 789}
	}
	{Entity "spawn_point" 0x9050
		{Position 3344.6 1845.87}
		{xform zl 39.15}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 790}
	}
	{Entity "spawn_point" 0x9052
		{Position 3007.9 735.3}
		{xform zl 39.15}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 791}
	}
	{Entity "spawn_point" 0x9053
		{Position 1013.04 3759.85}
		{xform zl -151.8}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 792}
	}
	{Entity "spawn_point" 0x9054
		{Position 1331.68 5046.73}
		{xform zl -10.67}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 793}
	}
	{Entity "spawn_point" 0x9055
		{Position 1803.23 3513.78}
		{xform zl -10.67}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 794}
	}
	{Entity "spawn_point" 0x9058
		{Position 246.94 3911.58}
		{xform zl -151.8}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 795}
	}
	{Entity "spawn_point" 0x9066
		{Position -1172.23 4315.79}
		{xform zl -73.15}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 796}
	}
	{Entity "spawn_point" 0x9068
		{Position -1716.4 5214.42}
		{xform zl -124.24}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 797}
	}
	{Entity "spawn_point" 0x9069
		{Position 1474.65 6052.91}
		{xform zl -10.67}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 798}
	}
	{Entity "spawn_point" 0x906c
		{Position 1831.69 4015.02}
		{xform zl -10.67}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 799}
	}
	{Entity "spawn_point" 0x906d
		{Position -3350.51 1948.91}
		{xform zl 9.35}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 800}
	}
	{Entity "spawn_point" 0x906f
		{Position -3160.46 3824.16}
		{xform zl -36.71}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 801}
	}
	{Entity "spawn_point" 0x9070
		{Position -4916.34 1743.3}
		{xform zl -116.58}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 802}
	}
	{Entity "spawn_point" 0x9072
		{Position -6726.59 857.42}
		{xform zl -84.81}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 803}
	}
	{Entity "spawn_point" 0x9073
		{Position -4230.99 -452.42}
		{xform zl -82.8}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 804}
	}
	{Entity "spawn_point" 0x9076
		{Position -2784.85 5194.96}
		{xform zl 9.35}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 805}
	}
	{Entity "spawn_point" 0x9077
		{Position -6093.77 955.52}
		{xform zl -112.85}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 806}
	}
	{Entity "spawn_point" 0x9079
		{Position -3133.91 1476.03}
		{xform zl 9.35}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 807}
	}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x9002}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x9003}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x9004}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x9005}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x9006}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x9007}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x9008}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x9009}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x900a}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x900b}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x900c}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x900d}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x900e}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x900f}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x9010}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x9011}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x9012}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x9013}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x9014}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x9015}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x9016}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x9017}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x9018}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x9019}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x901a}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x901b}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x901c}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x901d}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x901e}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x901f}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x9020}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x9022}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x9023}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x9026}
	{Tags "cmp_def" "4_b_3_mg" "4_a_3_mg" 0x9027}
	{Tags "cmp_def" "4_b_3_mg" "4_a_3_mg" 0x902a}
	{Tags "cmp_def" "4_b_3_mg" "4_a_3_mg" 0x902c}
	{Tags "cmp_def" "4_b_3_mg" "4_a_3_mg" 0x9030}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x9031}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x9033}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x9034}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x9036}
	{Tags "cmp_def" "2_b_3_mg" "2_a_3_mg" 0x9037}
	{Tags "cmp_def" "2_b_3_mg" "2_a_3_mg" 0x903a}
	{Tags "cmp_def" "2_b_3_mg" "2_a_3_mg" 0x903b}
	{Tags "cmp_def" "2_b_3_mg" "2_a_3_mg" 0x903d}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x9041}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x9043}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x9044}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x9046}
	{Tags "cmp_def" "1_b_3_mg" "1_a_3_mg" 0x9047}
	{Tags "cmp_def" "1_b_3_mg" "1_a_3_mg" 0x904f}
	{Tags "cmp_def" "1_b_3_mg" "1_a_3_mg" 0x9050}
	{Tags "cmp_def" "1_b_3_mg" "1_a_3_mg" 0x9052}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x9053}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x9054}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x9055}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x9058}
	{Tags "cmp_def" "3_b_3_mg" "3_a_3_mg" 0x9066}
	{Tags "cmp_def" "3_b_3_mg" "3_a_3_mg" 0x9068}
	{Tags "cmp_def" "3_b_3_mg" "3_a_3_mg" 0x9069}
	{Tags "cmp_def" "3_b_3_mg" "3_a_3_mg" 0x906c}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x906d}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x906f}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x9070}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x9072}
	{Tags "cmp_def" "5_b_3_mg" "5_a_3_mg" 0x9073}
	{Tags "cmp_def" "5_b_3_mg" "5_a_3_mg" 0x9076}
	{Tags "cmp_def" "5_b_3_mg" "5_a_3_mg" 0x9077}
	{Tags "cmp_def" "5_b_3_mg" "5_a_3_mg" 0x9079}