	{Human "" 0x8000
		{Position -3044.48 -12539.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 1}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8001
		{Position -3110.5 -12539.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 2}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8002
		{Position -3042.16 -12482}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 3}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8003
		{Position -3108.18 -12481.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 4}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8004
		{Position -3043.32 -12427.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 5}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8005
		{Position -3109.34 -12427.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 6}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8006
		{Position -3037.53 -12365.4}
		{xform zl 50.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 7}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8007
		{Position -3107.19 -12369.6}
		{xform zl 5.99}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 8}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8008
		{Position -3185.49 -12534.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 9}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8009
		{Position -3251.51 -12534.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 10}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x800a
		{Position -3183.18 -12477.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 11}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x800b
		{Position -3249.2 -12477}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 12}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x800c
		{Position -3184.33 -12422.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 13}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x800d
		{Position -3250.35 -12422.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 14}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x800e
		{Position -3182.02 -12365.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 15}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x800f
		{Position -3248.04 -12365.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 16}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8010
		{Position -3042.03 -12299.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 17}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8011
		{Position -3108.05 -12299.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 18}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8012
		{Position -3039.72 -12242.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 19}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8013
		{Position -3105.85 -12242.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 20}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8014
		{Position -3040.87 -12187.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 21}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8015
		{Position -3106.89 -12187.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 22}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8016
		{Position -3036.62 -12124.6}
		{xform zl 54}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 23}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8017
		{Position -3104.58 -12130.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 24}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8018
		{Position -3183.04 -12294.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 25}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8019
		{Position -3249.06 -12294.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 26}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x801a
		{Position -3180.73 -12237.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 27}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x801b
		{Position -3246.75 -12237.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 28}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x801c
		{Position -3181.88 -12183}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 29}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x801d
		{Position -3247.9 -12182.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 30}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x801e
		{Position -3178.53 -12125.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 31}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x801f
		{Position -3245.59 -12125.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 32}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8020
		{Position -3316.63 -12528.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 33}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8021
		{Position -3382.65 -12528.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 34}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8022
		{Position -3314.32 -12471}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 35}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8023
		{Position -3380.34 -12470.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 36}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8024
		{Position -3315.47 -12416.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 37}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8025
		{Position -3382.45 -12411.3}
		{xform zl 54.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 38}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8026
		{Position -3313.16 -12359.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 39}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8027
		{Position -3384.58 -12357.5}
		{xform zl 52.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 40}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8028
		{Position -3457.64 -12523.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 41}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8029
		{Position -3523.66 -12523.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 42}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x802a
		{Position -3455.33 -12466.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 43}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x802b
		{Position -3519.74 -12470.1}
		{xform zl -39}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 44}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x802c
		{Position -3451.78 -12408.3}
		{xform zl 34.75}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 45}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x802d
		{Position -3522.36 -12411.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 46}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x802e
		{Position -3454.17 -12354.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 47}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x802f
		{Position -3517.42 -12349.5}
		{xform zl 40.78}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 48}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8030
		{Position -3314.19 -12288.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 49}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8031
		{Position -3380.21 -12288.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 50}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8032
		{Position -3311.17 -12230.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 51}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8033
		{Position -3378.01 -12231.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 52}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8034
		{Position -3313.03 -12176.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 53}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8035
		{Position -3379.05 -12176.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 54}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8036
		{Position -3307.38 -12116.1}
		{xform zl 22.85}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 55}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8037
		{Position -3376.74 -12119.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 56}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8038
		{Position -3455.2 -12283.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 57}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8039
		{Position -3521.22 -12283.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 58}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x803a
		{Position -3452.89 -12226.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 59}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x803b
		{Position -3518.81 -12221.4}
		{xform zl 39}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 60}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x803c
		{Position -3454.04 -12172}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 61}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x803d
		{Position -3520.72 -12174.8}
		{xform zl -54.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 62}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x803e
		{Position -3447.91 -12109.4}
		{xform zl 53.19}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 63}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x803f
		{Position -3515.61 -12114.3}
		{xform zl -15.22}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 64}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8040
		{Position -3577.1 -12527.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 65}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8041
		{Position -3643.12 -12527.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 66}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8042
		{Position -3574.79 -12470}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 67}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8043
		{Position -3640.81 -12469.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 68}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8044
		{Position -3575.94 -12415.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 69}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8045
		{Position -3641.96 -12415.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 70}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8046
		{Position -3573.63 -12358.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 71}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8047
		{Position -3645.05 -12356.5}
		{xform zl 52.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 72}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8048
		{Position -3718.11 -12522.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 73}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8049
		{Position -3784.13 -12522.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 74}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x804a
		{Position -3715.8 -12465.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 75}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x804b
		{Position -3781.82 -12465}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 76}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x804c
		{Position -3716.94 -12410.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 77}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x804d
		{Position -3782.97 -12410.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 78}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x804e
		{Position -3714.63 -12353.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 79}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x804f
		{Position -3780.65 -12353.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 80}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8050
		{Position -3574.66 -12287.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 81}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8051
		{Position -3640.68 -12287.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 82}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8052
		{Position -3572.35 -12230.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 83}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8053
		{Position -3634.86 -12226.3}
		{xform zl 44.29}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 84}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8054
		{Position -3573.5 -12175.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 85}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8055
		{Position -3639.52 -12175.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 86}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8056
		{Position -3571.19 -12118.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 87}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8057
		{Position -3633.3 -12114}
		{xform zl 42.52}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 88}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8058
		{Position -3715.67 -12282.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 89}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8059
		{Position -3781.69 -12282.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 90}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x805a
		{Position -3710.87 -12222}
		{xform zl 35.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 91}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x805b
		{Position -3779.38 -12225.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 92}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x805c
		{Position -3714.51 -12171}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 93}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x805d
		{Position -3780.53 -12170.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 94}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x805e
		{Position -3711.49 -12113.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 95}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x805f
		{Position -3778.22 -12113.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 96}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8060
		{Position -3849.26 -12516.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 97}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8061
		{Position -3915.28 -12516.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 98}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8062
		{Position -3846.94 -12459}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 99}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8063
		{Position -3912.97 -12458.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 100}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8064
		{Position -3848.1 -12404.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 101}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8065
		{Position -3914.12 -12404.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 102}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8066
		{Position -3840.84 -12345.2}
		{xform zl 22.06}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 103}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8067
		{Position -3917.21 -12345.5}
		{xform zl 52.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 104}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8068
		{Position -3990.27 -12511.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 105}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8069
		{Position -4056.29 -12511.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 106}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x806a
		{Position -3987.96 -12454.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 107}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x806b
		{Position -4053.98 -12454}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 108}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x806c
		{Position -3989.11 -12399.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 109}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x806d
		{Position -4055.13 -12399.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 110}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x806e
		{Position -3986.8 -12342.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 111}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x806f
		{Position -4052.82 -12342.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 112}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8070
		{Position -3846.82 -12276.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 113}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8071
		{Position -3912.84 -12276.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 114}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8072
		{Position -3841.19 -12214.1}
		{xform zl 53.44}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 115}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8073
		{Position -3910.63 -12219.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 116}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8074
		{Position -3845.65 -12164.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 117}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8075
		{Position -3915.37 -12169.1}
		{xform zl -85.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 118}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8076
		{Position -3841.35 -12107.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 119}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8077
		{Position -3905.78 -12102.9}
		{xform zl 33.72}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 120}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8078
		{Position -3987.83 -12271.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 121}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8079
		{Position -4053.85 -12271.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 122}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x807a
		{Position -3985.52 -12214.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 123}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x807b
		{Position -4051.54 -12214.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 124}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x807c
		{Position -3986.67 -12160}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 125}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x807d
		{Position -4052.69 -12159.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 126}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x807e
		{Position -3983.79 -12102.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 127}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x807f
		{Position -4049.72 -12102.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 128}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc000
		{Position -4111.52 -12511.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 257}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc001
		{Position -4177.54 -12511}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 258}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc002
		{Position -4109.22 -12453.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 259}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc003
		{Position -4175.24 -12453.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 260}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc004
		{Position -4110.37 -12399.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 261}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc005
		{Position -4176.38 -12399.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 262}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc006
		{Position -4108.06 -12341.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 263}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc007
		{Position -4174.08 -12341.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 264}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc008
		{Position -4109.09 -12271.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 265}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc009
		{Position -4175.11 -12271.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 266}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc00a
		{Position -4106.77 -12213.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 267}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc00b
		{Position -4172.79 -12213.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 268}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc00c
		{Position -4107.92 -12159.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 269}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc00d
		{Position -4173.94 -12159.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 270}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc00e
		{Position -4105.04 -12101.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 271}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc00f
		{Position -4170.97 -12101.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 272}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc010
		{Position -2908.09 -12394.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 273}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc011
		{Position -2974.11 -12394.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 274}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc012
		{Position -2905.78 -12336.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 275}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc013
		{Position -2971.8 -12336.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 276}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc014
		{Position -2906.93 -12282.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 277}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc015
		{Position -2972.95 -12282.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 278}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8080
		{Position -4300.25 -12301.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 129}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8081
		{Position -4301.79 -12256.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 130}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8082
		{Position -4295.69 -12215.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 131}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8083
		{Position -4294.33 -12178}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 132}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8084
		{Position -4299.9 -12338.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 133}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8085
		{Position -4357.27 -12304}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 134}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8086
		{Position -4358.81 -12258.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 135}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8087
		{Position -4352.72 -12217.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 136}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8088
		{Position -4351.36 -12180.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 137}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8089
		{Position -4356.93 -12340.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 138}
		{FsmState "stand_noaim"}
	}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8000}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8001}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8002}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8003}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8004}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8005}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8006}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8007}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8008}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8009}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x800a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x800b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x800c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x800d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x800e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x800f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8010}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" "poop" 0x8011}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8012}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8013}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8014}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8015}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8016}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8017}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8018}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8019}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x801a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x801b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x801c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x801d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x801e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x801f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8020}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8021}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8022}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8023}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8024}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8025}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8026}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8027}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8028}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8029}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x802a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x802b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x802c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x802d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x802e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x802f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8030}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8031}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8032}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8033}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8034}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8035}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8036}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8037}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8038}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8039}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x803a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x803b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x803c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x803d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x803e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x803f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8040}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8041}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8042}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8043}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8044}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8045}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8046}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8047}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8048}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8049}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x804a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x804b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x804c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x804d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x804e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x804f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8050}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8051}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8052}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8053}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8054}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8055}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8056}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8057}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8058}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8059}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x805a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x805b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x805c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x805d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x805e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x805f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8060}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8061}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8062}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8063}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8064}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8065}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8066}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8067}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8068}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8069}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x806a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x806b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x806c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x806d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x806e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x806f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8070}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8071}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8072}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8073}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8074}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8075}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8076}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8077}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8078}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8079}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x807a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x807b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x807c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x807d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x807e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x807f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc000}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc001}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc002}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc003}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc004}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc005}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc006}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc007}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc008}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc009}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc00a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc00b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc00c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc00d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc00e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc00f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc010}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc011}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc012}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc013}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc014}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0xc015}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8080}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8081}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8082}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8083}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8084}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8085}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8086}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8087}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8088}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "cmp_def" 0x8089}
	{Inventory 0x8000
		{box
			{clear}
		}
	}
	{Inventory 0x8001
		{box
			{clear}
		}
	}
	{Inventory 0x8002
		{box
			{clear}
		}
	}
	{Inventory 0x8003
		{box
			{clear}
		}
	}
	{Inventory 0x8004
		{box
			{clear}
		}
	}
	{Inventory 0x8005
		{box
			{clear}
		}
	}
	{Inventory 0x8006
		{box
			{clear}
		}
	}
	{Inventory 0x8007
		{box
			{clear}
		}
	}
	{Inventory 0x8008
		{box
			{clear}
		}
	}
	{Inventory 0x8009
		{box
			{clear}
		}
	}
	{Inventory 0x800a
		{box
			{clear}
		}
	}
	{Inventory 0x800b
		{box
			{clear}
		}
	}
	{Inventory 0x800c
		{box
			{clear}
		}
	}
	{Inventory 0x800d
		{box
			{clear}
		}
	}
	{Inventory 0x800e
		{box
			{clear}
		}
	}
	{Inventory 0x800f
		{box
			{clear}
		}
	}
	{Inventory 0x8010
		{box
			{clear}
		}
	}
	{Inventory 0x8011
		{box
			{clear}
		}
	}
	{Inventory 0x8012
		{box
			{clear}
		}
	}
	{Inventory 0x8013
		{box
			{clear}
		}
	}
	{Inventory 0x8014
		{box
			{clear}
		}
	}
	{Inventory 0x8015
		{box
			{clear}
		}
	}
	{Inventory 0x8016
		{box
			{clear}
		}
	}
	{Inventory 0x8017
		{box
			{clear}
		}
	}
	{Inventory 0x8018
		{box
			{clear}
		}
	}
	{Inventory 0x8019
		{box
			{clear}
		}
	}
	{Inventory 0x801a
		{box
			{clear}
		}
	}
	{Inventory 0x801b
		{box
			{clear}
		}
	}
	{Inventory 0x801c
		{box
			{clear}
		}
	}
	{Inventory 0x801d
		{box
			{clear}
		}
	}
	{Inventory 0x801e
		{box
			{clear}
		}
	}
	{Inventory 0x801f
		{box
			{clear}
		}
	}
	{Inventory 0x8020
		{box
			{clear}
		}
	}
	{Inventory 0x8021
		{box
			{clear}
		}
	}
	{Inventory 0x8022
		{box
			{clear}
		}
	}
	{Inventory 0x8023
		{box
			{clear}
		}
	}
	{Inventory 0x8024
		{box
			{clear}
		}
	}
	{Inventory 0x8025
		{box
			{clear}
		}
	}
	{Inventory 0x8026
		{box
			{clear}
		}
	}
	{Inventory 0x8027
		{box
			{clear}
		}
	}
	{Inventory 0x8028
		{box
			{clear}
		}
	}
	{Inventory 0x8029
		{box
			{clear}
		}
	}
	{Inventory 0x802a
		{box
			{clear}
		}
	}
	{Inventory 0x802b
		{box
			{clear}
		}
	}
	{Inventory 0x802c
		{box
			{clear}
		}
	}
	{Inventory 0x802d
		{box
			{clear}
		}
	}
	{Inventory 0x802e
		{box
			{clear}
		}
	}
	{Inventory 0x802f
		{box
			{clear}
		}
	}
	{Inventory 0x8030
		{box
			{clear}
		}
	}
	{Inventory 0x8031
		{box
			{clear}
		}
	}
	{Inventory 0x8032
		{box
			{clear}
		}
	}
	{Inventory 0x8033
		{box
			{clear}
		}
	}
	{Inventory 0x8034
		{box
			{clear}
		}
	}
	{Inventory 0x8035
		{box
			{clear}
		}
	}
	{Inventory 0x8036
		{box
			{clear}
		}
	}
	{Inventory 0x8037
		{box
			{clear}
		}
	}
	{Inventory 0x8038
		{box
			{clear}
		}
	}
	{Inventory 0x8039
		{box
			{clear}
		}
	}
	{Inventory 0x803a
		{box
			{clear}
		}
	}
	{Inventory 0x803b
		{box
			{clear}
		}
	}
	{Inventory 0x803c
		{box
			{clear}
		}
	}
	{Inventory 0x803d
		{box
			{clear}
		}
	}
	{Inventory 0x803e
		{box
			{clear}
		}
	}
	{Inventory 0x803f
		{box
			{clear}
		}
	}
	{Inventory 0x8040
		{box
			{clear}
		}
	}
	{Inventory 0x8041
		{box
			{clear}
		}
	}
	{Inventory 0x8042
		{box
			{clear}
		}
	}
	{Inventory 0x8043
		{box
			{clear}
		}
	}
	{Inventory 0x8044
		{box
			{clear}
		}
	}
	{Inventory 0x8045
		{box
			{clear}
		}
	}
	{Inventory 0x8046
		{box
			{clear}
		}
	}
	{Inventory 0x8047
		{box
			{clear}
		}
	}
	{Inventory 0x8048
		{box
			{clear}
		}
	}
	{Inventory 0x8049
		{box
			{clear}
		}
	}
	{Inventory 0x804a
		{box
			{clear}
		}
	}
	{Inventory 0x804b
		{box
			{clear}
		}
	}
	{Inventory 0x804c
		{box
			{clear}
		}
	}
	{Inventory 0x804d
		{box
			{clear}
		}
	}
	{Inventory 0x804e
		{box
			{clear}
		}
	}
	{Inventory 0x804f
		{box
			{clear}
		}
	}
	{Inventory 0x8050
		{box
			{clear}
		}
	}
	{Inventory 0x8051
		{box
			{clear}
		}
	}
	{Inventory 0x8052
		{box
			{clear}
		}
	}
	{Inventory 0x8053
		{box
			{clear}
		}
	}
	{Inventory 0x8054
		{box
			{clear}
		}
	}
	{Inventory 0x8055
		{box
			{clear}
		}
	}
	{Inventory 0x8056
		{box
			{clear}
		}
	}
	{Inventory 0x8057
		{box
			{clear}
		}
	}
	{Inventory 0x8058
		{box
			{clear}
		}
	}
	{Inventory 0x8059
		{box
			{clear}
		}
	}
	{Inventory 0x805a
		{box
			{clear}
		}
	}
	{Inventory 0x805b
		{box
			{clear}
		}
	}
	{Inventory 0x805c
		{box
			{clear}
		}
	}
	{Inventory 0x805d
		{box
			{clear}
		}
	}
	{Inventory 0x805e
		{box
			{clear}
		}
	}
	{Inventory 0x805f
		{box
			{clear}
		}
	}
	{Inventory 0x8060
		{box
			{clear}
		}
	}
	{Inventory 0x8061
		{box
			{clear}
		}
	}
	{Inventory 0x8062
		{box
			{clear}
		}
	}
	{Inventory 0x8063
		{box
			{clear}
		}
	}
	{Inventory 0x8064
		{box
			{clear}
		}
	}
	{Inventory 0x8065
		{box
			{clear}
		}
	}
	{Inventory 0x8066
		{box
			{clear}
		}
	}
	{Inventory 0x8067
		{box
			{clear}
		}
	}
	{Inventory 0x8068
		{box
			{clear}
		}
	}
	{Inventory 0x8069
		{box
			{clear}
		}
	}
	{Inventory 0x806a
		{box
			{clear}
		}
	}
	{Inventory 0x806b
		{box
			{clear}
		}
	}
	{Inventory 0x806c
		{box
			{clear}
		}
	}
	{Inventory 0x806d
		{box
			{clear}
		}
	}
	{Inventory 0x806e
		{box
			{clear}
		}
	}
	{Inventory 0x806f
		{box
			{clear}
		}
	}
	{Inventory 0x8070
		{box
			{clear}
		}
	}
	{Inventory 0x8071
		{box
			{clear}
		}
	}
	{Inventory 0x8072
		{box
			{clear}
		}
	}
	{Inventory 0x8073
		{box
			{clear}
		}
	}
	{Inventory 0x8074
		{box
			{clear}
		}
	}
	{Inventory 0x8075
		{box
			{clear}
		}
	}
	{Inventory 0x8076
		{box
			{clear}
		}
	}
	{Inventory 0x8077
		{box
			{clear}
		}
	}
	{Inventory 0x8078
		{box
			{clear}
		}
	}
	{Inventory 0x8079
		{box
			{clear}
		}
	}
	{Inventory 0x807a
		{box
			{clear}
		}
	}
	{Inventory 0x807b
		{box
			{clear}
		}
	}
	{Inventory 0x807c
		{box
			{clear}
		}
	}
	{Inventory 0x807d
		{box
			{clear}
		}
	}
	{Inventory 0x807e
		{box
			{clear}
		}
	}
	{Inventory 0x807f
		{box
			{clear}
		}
	}
	{Inventory 0xc000
		{box
			{clear}
		}
	}
	{Inventory 0xc001
		{box
			{clear}
		}
	}
	{Inventory 0xc002
		{box
			{clear}
		}
	}
	{Inventory 0xc003
		{box
			{clear}
		}
	}
	{Inventory 0xc004
		{box
			{clear}
		}
	}
	{Inventory 0xc005
		{box
			{clear}
		}
	}
	{Inventory 0xc006
		{box
			{clear}
		}
	}
	{Inventory 0xc007
		{box
			{clear}
		}
	}
	{Inventory 0xc008
		{box
			{clear}
		}
	}
	{Inventory 0xc009
		{box
			{clear}
		}
	}
	{Inventory 0xc00a
		{box
			{clear}
		}
	}
	{Inventory 0xc00b
		{box
			{clear}
		}
	}
	{Inventory 0xc00c
		{box
			{clear}
		}
	}
	{Inventory 0xc00d
		{box
			{clear}
		}
	}
	{Inventory 0xc00e
		{box
			{clear}
		}
	}
	{Inventory 0xc00f
		{box
			{clear}
		}
	}
	{Inventory 0xc010
		{box
			{clear}
		}
	}
	{Inventory 0xc011
		{box
			{clear}
		}
	}
	{Inventory 0xc012
		{box
			{clear}
		}
	}
	{Inventory 0xc013
		{box
			{clear}
		}
	}
	{Inventory 0xc014
		{box
			{clear}
		}
	}
	{Inventory 0xc015
		{box
			{clear}
		}
	}
	{Inventory 0x8080
		{box
			{clear}
		}
	}
	{Inventory 0x8081
		{box
			{clear}
		}
	}
	{Inventory 0x8082
		{box
			{clear}
		}
	}
	{Inventory 0x8083
		{box
			{clear}
		}
	}
	{Inventory 0x8084
		{box
			{clear}
		}
	}
	{Inventory 0x8085
		{box
			{clear}
		}
	}
	{Inventory 0x8086
		{box
			{clear}
		}
	}
	{Inventory 0x8087
		{box
			{clear}
		}
	}
	{Inventory 0x8088
		{box
			{clear}
		}
	}
	{Inventory 0x8089
		{box
			{clear}
		}
	}
	{Brain 0x8000
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8001
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8002
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8003
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8004
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8005
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8006
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8007
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8008
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8009
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x800a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x800b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x800c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x800d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x800e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x800f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8010
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8011
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8012
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8013
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8014
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8015
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8016
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8017
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8018
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8019
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x801a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x801b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x801c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x801d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x801e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x801f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8020
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8021
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8022
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8023
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8024
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8025
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8026
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8027
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8028
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8029
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x802a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x802b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x802c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x802d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x802e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x802f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8030
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8031
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8032
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8033
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8034
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8035
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8036
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8037
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8038
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8039
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x803a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x803b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x803c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x803d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x803e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x803f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8040
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8041
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8042
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8043
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8044
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8045
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8046
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8047
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8048
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8049
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x804a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x804b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x804c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x804d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x804e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x804f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8050
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8051
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8052
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8053
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8054
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8055
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8056
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8057
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8058
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8059
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x805a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x805b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x805c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x805d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x805e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x805f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8060
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8061
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8062
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8063
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8064
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8065
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8066
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8067
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8068
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8069
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x806a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x806b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x806c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x806d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x806e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x806f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8070
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8071
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8072
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8073
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8074
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8075
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8076
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8077
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8078
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8079
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x807a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x807b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x807c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x807d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x807e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x807f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc000
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc001
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc002
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc003
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc004
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc005
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc006
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc007
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc008
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc009
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc00a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc00b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc00c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc00d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc00e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc00f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc010
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc011
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc012
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc013
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc014
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc015
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8080
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8081
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8082
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8083
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8084
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8085
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8086
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8087
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8088
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8089
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}