	{Entity "spawn_point" 0xcf38
		{Position 975 2520}
		{xform zl -19.99}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3957}
	}
	{Entity "spawn_point" 0xcf39
		{Position -945 2145}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3958}
	}
	{Entity "spawn_point" 0xcf3a
		{Position -465 3020}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3959}
	}
	{Entity "spawn_point" 0xcf3b
		{Position -750 2010}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3960}
	}
	{Entity "spawn_point" 0xcf3c
		{Position -2105 125}
		{xform zl -30}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3961}
	}
	{Entity "spawn_point" 0xcf3d
		{Position -3960 660}
		{xform zl -160}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3962}
	}
	{Entity "spawn_point" 0xcf3e
		{Position -3110 -1285}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3963}
	}
	{Entity "spawn_point" 0xcf3f
		{Position -1380 -3420}
		{xform zl 20}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3964}
	}
	{Entity "spawn_point" 0xcf40
		{Position 755 4540}
		{xform zl -30}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3965}
	}
	{Entity "spawn_point" 0xcf41
		{Position -560 3745}
		{xform zl 70}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3966}
	}
	{Entity "spawn_point" 0xcf42
		{Position -3075 2800}
		{xform zl -179.99}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3967}
	}
	{Entity "spawn_point" 0xcf43
		{Position -1890 2675}
		{xform zl -140}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3968}
	}
	{Entity "spawn_point" 0xcf44
		{Position 520 -2740}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3969}
	}
	{Entity "spawn_point" 0xcf45
		{Position 700 -3570}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3970}
	}
	{Entity "spawn_point" 0xcf46
		{Position 2085 -1620}
		{xform zl 20}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3971}
	}
	{Entity "spawn_point" 0xcf47
		{Position 1925 -5230}
		{xform zl 40}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3972}
	}
	{Entity "spawn_point" 0xcf48
		{Position -2330 4475}
		{xform zl -20}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3973}
	}
	{Entity "spawn_point" 0xcf49
		{Position -1930 7060}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3974}
	}
	{Entity "spawn_point" 0xcf4a
		{Position -4120 5220}
		{xform zl -130}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3975}
	}
	{Entity "spawn_point" 0xcf4b
		{Position -3670 3010}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3976}
	}



	{Entity "spawn_point" 0x8000
		{Position -878.33 2706}
		{xform zl 165.17}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 1}
	}
	{Entity "spawn_point" 0x8001
		{Position -2847.88 -1387.83}
		{xform zl 157.22}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 2}
	}
	{Entity "spawn_point" 0x8002
		{Position -1238.01 3438.14}
		{xform zl -124.82}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3}
	}
	{Entity "spawn_point" 0x8003
		{Position 393.63 -3179.09}
		{xform zl 178.55}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 4}
	}
	{Entity "spawn_point" 0x8004
		{Position -3833.8 5136.73}
		{xform zl -145.98}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 5}
	}
	{Entity "spawn_point" 0x8005
		{Position -1792.86 4271.88}
		{xform zl -168.04}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 6}
	}
	{Entity "spawn_point" 0x8006
		{Position -455.58 1535.06}
		{xform zl -163.96}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 7}
	}
	{Entity "spawn_point" 0x8007
		{Position -3351.46 6374.51}
		{xform zl -2.99}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 8}
	}
	{Entity "spawn_point" 0x8008
		{Position -3061.62 -565.15}
		{xform zl 137.85}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 9}
	}
	{Entity "spawn_point" 0x8009
		{Position 937.06 -2794.57}
		{xform zl 132.38}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 10}
	}
	{Entity "spawn_point" 0x8120
		{Position 641.42 -4267.48}
		{xform zl 178.55}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 611}
	}
	{Entity "spawn_point" 0x8121
		{Position 1783.12 -4224.91}
		{xform zl 8.12}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 612}
	}
	{Entity "spawn_point" 0x8122
		{Position 1882.79 -2074.45}
		{xform zl 8.12}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 613}
	}
	{Entity "spawn_point" 0x8124
		{Position 709.95 -2408.73}
		{xform zl 178.55}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 614}
	}
	{Entity "spawn_point" 0x8126
		{Position 1305.66 -2051.49}
		{xform zl -169.7}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 615}
	}
	{Entity "spawn_point" 0x8128
		{Position -23.64 -3731.55}
		{xform zl -169.7}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 616}
	}
	{Entity "spawn_point" 0x812a
		{Position 1935.22 -4751.83}
		{xform zl 8.12}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 617}
	}
	{Entity "spawn_point" 0x812c
		{Position 2052.22 -2389.86}
		{xform zl 8.12}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 618}
	}
	{Entity "spawn_point" 0x812e
		{Position -3418.63 137.39}
		{xform zl 175.19}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 619}
	}
	{Entity "spawn_point" 0x8130
		{Position -3147.81 -1852.11}
		{xform zl 178.53}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 620}
	}
	{Entity "spawn_point" 0x8132
		{Position -1579.13 -846.86}
		{xform zl 36.45}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 621}
	}
	{Entity "spawn_point" 0x8134
		{Position -1563.76 -2067.78}
		{xform zl 36.45}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 622}
	}
	{Entity "spawn_point" 0x8136
		{Position -235.87 -1937.13}
		{xform zl 53.51}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 623}
	}
	{Entity "spawn_point" 0x8138
		{Position -1912.72 755.52}
		{xform zl 31.35}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 624}
	}
	{Entity "spawn_point" 0x813a
		{Position -3400.17 1345.95}
		{xform zl -158.28}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 625}
	}
	{Entity "spawn_point" 0x813c
		{Position -2284.53 -3096.6}
		{xform zl -157.64}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 626}
	}
	{Entity "spawn_point" 0x813e
		{Position -637.03 1220.24}
		{xform zl -163.96}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 627}
	}
	{Entity "spawn_point" 0x8140
		{Position 309.01 1119.88}
		{xform zl 4.43}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 628}
	}
	{Entity "spawn_point" 0x8142
		{Position 1084.39 2066.43}
		{xform zl 4.43}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 629}
	}
	{Entity "spawn_point" 0x8144
		{Position -803.56 3082.59}
		{xform zl -163.96}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 630}
	}
	{Entity "spawn_point" 0x8146
		{Position -2358.77 1511.32}
		{xform zl 145.14}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 631}
	}
	{Entity "spawn_point" 0x8148
		{Position -1390.61 -260.72}
		{xform zl 167.18}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 632}
	}
	{Entity "spawn_point" 0x8230
		{Position 1854.55 2215.12}
		{xform zl 4.43}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 633}
	}
	{Entity "spawn_point" 0x8231
		{Position -543.15 -220.58}
		{xform zl 4.43}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 634}
	}
	{Entity "spawn_point" 0x8232
		{Position 161.98 4753.89 -4}
		{xform zl 32.81}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 635}
	}
	{Entity "spawn_point" 0x8234
		{Position -127.8 5312.79 -4}
		{xform zl 15.58}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 636}
	}
	{Entity "spawn_point" 0x8235
		{Position -1936.7 3074.02}
		{xform zl -124.82}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 637}
	}
	{Entity "spawn_point" 0x8236
		{Position -2013.79 3138.33}
		{xform zl -124.82}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 638}
	}
	{Entity "spawn_point" 0x8237
		{Position -717.05 6027.35 -44}
		{xform zl 32.81}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 639}
	}
	{Entity "spawn_point" 0x8239
		{Position -2681.82 3576.36 -4}
		{xform zl -139.62}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 640}
	}
	{Entity "spawn_point" 0x823b
		{Position -3145.4 2574.45 3.65}
		{xform zl -139.62}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 641}
	}
	{Entity "spawn_point" 0x823d
		{Position 1186.53 4121.6 -5}
		{xform zl 32.81}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 642}
	}
	{Entity "spawn_point" 0x823f
		{Position -4206.2 3648.25}
		{xform zl -140.12}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 643}
	}
	{Entity "spawn_point" 0x8241
		{Position -2000.46 4806.68}
		{xform zl -5.36}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 644}
	}
	{Entity "spawn_point" 0x8243
		{Position -2616.82 5499.3}
		{xform zl 21.71}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 645}
	}
	{Entity "spawn_point" 0x8247
		{Position -5453.9 4897.37}
		{xform zl -110.27}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 647}
	}
	{Entity "spawn_point" 0xc100
		{Position -3694.92 3271.56}
		{xform zl -110.64}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 646}
	}
	{Entity "spawn_point" 0xc101
		{Position -3345.91 2927.46}
		{xform zl -136.75}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 648}
	}
	{Entity "spawn_point" 0xc102
		{Position -3151.97 7062.69}
		{xform zl -5.36}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 649}
	}
	{Entity "spawn_point" 0xc103
		{Position -1625.51 4589.48}
		{xform zl -5.36}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 650}
	}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0xcf38}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0xcf39}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0xcf3a}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0xcf3b}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0xcf3c}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0xcf3d}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0xcf3e}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0xcf3f}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0xcf40}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0xcf41}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0xcf42}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0xcf43}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0xcf44}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0xcf45}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0xcf46}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0xcf47}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0xcf48}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0xcf49}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0xcf4a}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0xcf4b}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x8000}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x8001}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x8002}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x8003}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x8004}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x8005}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x8006}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x8007}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x8008}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x8009}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x8120}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x8121}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x8122}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x8124}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x8126}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x8128}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x812a}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x812c}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x812e}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x8130}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x8132}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x8134}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x8136}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x8138}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x813a}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x813c}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x813e}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x8140}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x8142}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x8144}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x8146}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x8148}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x8230}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x8231}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x8232}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x8234}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x8235}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x8236}
	{Tags "cmp_def" "3_a_1-3_mg" "3_b_1-3_mg" 0x8237}
	{Tags "cmp_def" "3_a_1-3_mg" "3_b_1-3_mg" 0x8239}
	{Tags "cmp_def" "3_a_1-3_mg" "3_b_1-3_mg" 0x823b}
	{Tags "cmp_def" "3_a_1-3_mg" "3_b_1-3_mg" 0x823d}
	{Tags "cmp_def" "5_a_1-3_mg" "5_b_1-3_mg" 0x823f}
	{Tags "cmp_def" "5_a_1-3_mg" "5_b_1-3_mg" 0x8241}
	{Tags "cmp_def" "5_a_1-3_mg" "5_b_1-3_mg" 0x8243}
	{Tags "cmp_def" "5_a_1-3_mg" "5_b_1-3_mg" 0x8247}
	{Tags "cmp_def" "5_a_1-3_mg" "5_b_1-3_mg" 0xc100}
	{Tags "cmp_def" "5_a_1-3_mg" "5_b_1-3_mg" 0xc101}
	{Tags "cmp_def" "5_a_1-3_mg" "5_b_1-3_mg" 0xc102}
	{Tags "cmp_def" "5_a_1-3_mg" "5_b_1-3_mg" 0xc103}