			{"ai_air_on"}
			{"arrows"}
			{"balance"}
			{"bot_army"}
			{"bots_spawnside"}
			{"dcg_error"}
			{"dcg_on"}
			{"def_team"}
			{"enemyid"}
			{"id_1st_enemy"}
			{"id_1st_player"}
			{"id_defenderbot"}
			{"music_intense"}
			{"user_is_defender"}
			{"user_nation"}
			{"user_team"}
			{"tier2"}

;//Temporary additions for CE Player Scripts 
			(include "../../map_scripts/conquest_enhanced_vars.inc")
		}
		{functions
			(include "../../map_scripts/conquest_enhanced_functions.inc")