			{"music_intense"}
			{"balance"}
			{"user_nation"}
			{"dcg_error"}
			{"dcg_on"}
			{"enemyid"}
			{"ai_air_on"}
			{"user_team"}
			{"def_team"}
			{"tier2"}
			{"arrows"}
			{"ai death count"}
			{"flag count"}
			{"player death count"}
			{"player tank count"}
			{"player arty count"}
			{"officeractions"}
			{"airscripts"}
			{"officerdocument"}
			{"officerdocument2"}
			{"partisan"}
			{"randomtimer"}
			{"defensetier"}
			{"radiocar"}
			{"readytodelete"}
			{"para_plane_side_start"}
			{"para_plane_index"}
			{"drop_behind_lines"}
			{"targeted_drop"}
			{"max_para_groups"}
			{"player_defending"}
			{event "talk_on"}