			{"tips"
				{desc "mission/multi/modexplain"}
				{primary}
			}
			{"radio truck"
				{desc "mission/multi/radiotruck"}
			}
			{"defenselevels"
				{desc "mission/multi/defenselevels"}
			}
			{"engineers"
				{desc "mission/multi/engineers"}
			}
			{"callin"
				{desc "mission/multi/callin"}
			}
			{"medics"
				{desc "mission/multi/medics"}
			}
			{"teleport"
				{desc "mission/multi/teleport"}
			}