;AUTOMATIC WEAPONRY
{"maxim"
	{on spawn
	    {tags add "HMG"}
		{tags add "soviet"}
		{tags add "maxim"}
	}
}
{"dshk_stan"
	{on spawn
	    {tags add "HMG"}
		{tags add "soviet"}
		{tags add "dshk_stan"}
	}
}
{"dshk_aa"
	{on spawn
	    {tags add "HMG"}
		{tags add "soviet"}
		{tags add "dshk_aa"}
	}
}
{"25mm_72k"
	{on spawn
	    {tags add "AAFLAK"}
		{tags add "soviet"}
		{tags add "25mm_72k"}
	}
}
{"37mm_61k"
	{on spawn
	    {tags add "AAFLAK"}
		{tags add "soviet"}
		{tags add "37mm_61k"}
	}
}


; AT WEAPONRY
{"m41_ampulomet"
	{on spawn
	    {tags add "light_at_gun"}
		{tags add "soviet"}
		{tags add "m41_ampulomet"}
	}
}
{"45mm_m37"
	{on spawn
	    {tags add "light_at_gun"}
		{tags add "soviet"}
		{tags add "45mm_m37"}
	}
}
{"45mm_m42"
	{on spawn
	    {tags add "light_at_gun"}
		{tags add "soviet"}
		{tags add "45mm_m42"}
	}
}
{"57mm_zis2"
	{on spawn
	    {tags add "medium_at_gun"}
		{tags add "soviet"}
		{tags add "57mm_zis2"}
	}
}
{"76mm_f22"
	{on spawn
	    {tags add "medium_at_gun"}
		{tags add "soviet"}
		{tags add "76_f22"}
	}
}
{"76mm_zis3"
	{on spawn
	    {tags add "medium_at_gun"}
		{tags add "soviet"}
		{tags add "76mm_zis3"}
	}
}
{"85mm_52k"
	{on spawn
	    {tags add "heavy_at_gun"}
		{tags add "soviet"}
		{tags add "85mm_52k"}
	}
}
{"100mm_bs3"
	{on spawn
	    {tags add "heavy_at_gun"}
		{tags add "soviet"}
		{tags add "100mm_bs3"}
	}
}


;HOWITZERS
{"76mm_m1927"
	{on spawn
    	{tags add "medium_at_gun"}
		{tags add "soviet"}
		{tags add "76mm_m1927"}
	}
}
{"76mm_m43"
	{on spawn
    	{tags add "medium_at_gun"}
		{tags add "soviet"}
		{tags add "76mm_m43"}
	}
}
{"82mm_bm37"
	{on spawn
		{tags add "artillery"}
		{tags add "soviet"}
		{tags add "82mm_bm37"}
	}
}
{"120mm_pm38"
	{on spawn
		{tags add "artillery"}
		{tags add "soviet"}
		{tags add "120mm_pm38"}
	}
}
{"122mm_m30"
	{on spawn
    	{tags add "artillery"}
		{tags add "soviet"}
		{tags add "122mm_m30"}
	}
}
{"122mm_a19"
	{on spawn
    	{tags add "artillery"}
	{tags add "heavy_artillery"}
		{tags add "soviet"}
		{tags add "122mm_a19"}
	}
}
{"152mm_ml20"
	{on spawn
    	{tags add "artillery"}
	{tags add "heavy_artillery"}
		{tags add "soviet"}
		{tags add "152mm_ml20"}
	}
}
{"203mm_b4"
	{on spawn
    	{tags add "super_heavy_artillery"}
    	{tags add "artillery"}
		{tags add "soviet"}
		{tags add "203mm_b4"}
	}
}
{"122mm_m3ai"
	{on spawn
    	{tags add "artillery"}
		{tags add "soviet"}
		{tags add "122mm_m30"}
		{tags add "no_scavenge"}
	}
}
{"122mm_a19ai"
	{on spawn
    	{tags add "artillery"}
	    {tags add "heavy_artillery"}
		{tags add "soviet"}
		{tags add "122mm_a19"}
		{tags add "no_scavenge"}
	}
}
{"152mm_ml20ai"
	{on spawn
    	{tags add "artillery"}
	    {tags add "heavy_artillery"}
		{tags add "soviet"}
		{tags add "152mm_ml20"}
		{tags add "no_scavenge"}
	}
}
{"203mm_b4ai"
	{on spawn
    	{tags add "super_heavy_artillery"}
    	{tags add "artillery"}
		{tags add "soviet"}
		{tags add "203mm_b4"}
		{tags add "no_scavenge"}
	}
}
{"su14"
	{on spawn
    	{tags add "super_heavy_artillery"}
    	{tags add "artillery"}
		{tags add "soviet"}
		{tags add "su14"}
		{tags add "no_scavenge"}
	}
}
{"su5"
	{on spawn
    	{tags add "artillery"}
		{tags add "soviet"}
		{tags add "su5"}
		{tags add "no_scavenge"}
	}
}

;_________________________________________________
;|               Wheeled vehicles                 |
;|________________________________________________|


{"gaz_aaa"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "gaz_aaa"}
    }
}
{"gaz_aaa_supply"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "gaz_aaa_supply"}
		{tags add "ammo"}
    }
}
{"gaz_fuel"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "gaz_fuel"}
    }
}
{"gaz_aaa_72k"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "gas_aaa_72k"}
	}
}
{"zis5"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "zis5"}
	}
}
{"zis5eng"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "zis5eng"}
	}
}
{"bm13_studebaker"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "rocket_artillery"}
		{tags add "soviet"}
		{tags add "bm13_studebaker"}
	}
}
{"bm31_12"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "rocket_artillery"}
		{tags add "soviet"}
		{tags add "bm31_12"}
	}
}
{"bm13_studebakerai"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "rocket_artillery"}
		{tags add "soviet"}
		{tags add "bm13_studebaker"}
		{tags add "no_scavenge"}
	}
}
{"bm31_12ai"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "rocket_artillery"}
		{tags add "soviet"}
		{tags add "bm31_12"}
		{tags add "no_scavenge"}
	}
}
{"gaz67b"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "gaz67b"}
	}
}
{"gaz67"
	{on spawn
    	{if not tagged "radiorus"
		    {tags add "radio_car"}
		}
		{tags add "soviet"}
		{tags add "gaz67"}
	}
}
{"ba20"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "ba20"}
	}
}
{"ba6"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "ba6"}
	}
}
{"ba64"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "ba64"}
	}
}
{"universal_carrier_rus"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "universal_carrier_rus"}
	}
}
{"mmg_carrier_rus"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "mmg_carrier_rus"}
	}
}
{"m3a1e1_scout_mgun"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "m3a1e1_scout_mgun"}
	}
}
{"yag10_29k"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "yag10_29k"}
	}
}
{"bm8-48"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "bm8-48"}
	}
}

{"ba10"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "ba10"}
	}
}
{"ba11"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "ba11"}
	}
}
{"bm8-48"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "bm8-48"}
	}
}

{"m3"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "m3"}
	}
}
{"m17"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "m17"}
	}
}
{"su57"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "soviet"}
		{tags add "su57"}
	}
}


;_________________________________________________
;|        Main Battle Tanks and SPGs              |
;|________________________________________________|

;LIGHT
{"t27"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "t27"}
	}
}
{"t37a"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "t37a"}
	}
}
{"t40"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "t40"}
	}
}
{"t30"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "t30"}
	}
}
{"t50"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "t50"}
	}
}
{"t60"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "t60"}
	}
}
{"t70"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "t70"}
	}
}
{"t70m"
	{on spawn
    	{tags add "light_tank"}
		{tags add "t70m"}
	}
}
{"t80"
	{on spawn
    	{tags add "light_tank"}
		{tags add "t80"}
	}
}
{"bm_8_24"
	{on spawn
    	{tags add "light_tank"}
		{tags add "bm_8_24"}
	}
}
{"at-1"
	{on spawn
    	{tags add "light_tank"}
		{tags add "at-1"}
	}
}

{"bt2_da2"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "bt2_da2"}
	}
}
{"bt2"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "bt2"}
	}
}
{"bt5"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "bt5"}
	}
}
{"bt7"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "bt7"}
	}
}
{"bt7a"
	{on spawn
    	{tags add "spg"}
		{tags add "soviet"}
		{tags add "bt7a"}
	}
}

{"t18"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "t18"}
	}
}
{"t26_31"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "t26_31"}
	}
}
{"kht26"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "kht26"}
	}
}
{"t26_33"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "t26_33"}
	}
}
{"t26_38"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "t26_38"}
	}
}
{"t26_39"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "t26_39"}
	}
}

{"valentine2"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "valentine2"}
	}
}
{"valentine7"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "valentine7"}
	}
}
{"valentine9"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "valentine9"}
	}
}

{"m3stuart"
	{on spawn
    	{tags add "light_tank"}
		{tags add "soviet"}
		{tags add "m3stuart"}
	}
}

;MEDIUM
{"matilda2"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "soviet"}
		{tags add "matilda2"}
	}
}
{"m4a2"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "soviet"}
		{tags add "m4a2"}
	}
}
{"m4a2_76w"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "soviet"}
		{tags add "m4a2_76w"}
	}
}

{"t28"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "soviet"}
		{tags add "t28"}
	}
}
{"t3476_40"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "soviet"}
		{tags add "t3476_40"}
	}
}
{"t3476_41"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "soviet"}
		{tags add "t3476_41"}
	}
}
{"t3457_41"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "soviet"}
		{tags add "t3457_41"}
	}
}
{"t3476_42"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "soviet"}
		{tags add "t3476_42"}
	}
}
{"t3476_43"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "soviet"}
		{tags add "t3476_43"}
	}
}
{"t3457_43"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "soviet"}
		{tags add "t3457_43"}
	}
}
{"t3476_43_flame"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "soviet"}
		{tags add "t3476_43_flame"}
	}
}
{"t3485_44"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "soviet"}
		{tags add "t3485_44"}
	}
}
{"t44"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "soviet"}
		{tags add "t44"}
	}
}
{"t44_122"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "soviet"}
		{tags add "t44_122"}
	}
}

;HEAVY
{"churchill3"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "soviet"}
		{tags add "churchill3"}
	}
}
{"kv1_40"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "soviet"}
		{tags add "kv1_40"}
	}
}
{"kv1e_40"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "soviet"}
		{tags add "kv1e_40"}
	}
}
{"kv1_41"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "soviet"}
		{tags add "kv1_41"}
	}
}
{"kv1e_41"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "soviet"}
		{tags add "kv1e_41"}
	}
}
{"kv2_40"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "soviet"}
		{tags add "kv2_40"}
	}
}
{"kv1s"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "soviet"}
		{tags add "kv1s"}
	}
}
{"kv85"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "soviet"}
		{tags add "kv85"}
	}
}
{"kv-122"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "soviet"}
		{tags add "kv-122"}
	}
}
{"kv220"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "soviet"}
		{tags add "kv220"}
	}
}
{"is1_43"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "soviet"}
		{tags add "is1_43"}
	}
}
{"is2_43"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "soviet"}
		{tags add "is2_43"}
	}
}
{"is2_44"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "soviet"}
		{tags add "is2_44"}
	}
}
{"is3"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "soviet"}
		{tags add "is3"}
	}
}

;SPG
{"zis30"
	{on spawn
    	{tags add "spg"}
		{tags add "soviet"}
		{tags add "zis30"}
	}
}
{"su76"
	{on spawn
    	{tags add "spg"}
		{tags add "soviet"}
		{tags add "su76"}
	}
}
{"su76i"
	{on spawn
    	{tags add "spg"}
		{tags add "soviet"}
		{tags add "su76i"}
	}
}
{"su85"
	{on spawn
    	{tags add "spg"}
		{tags add "soviet"}
		{tags add "su85"}
	}
}
{"su85m"
	{on spawn
    	{tags add "spg"}
		{tags add "soviet"}
		{tags add "su85m"}
	}
}
{"su100"
	{on spawn
    	{tags add "spg"}
		{tags add "soviet"}
		{tags add "su100"}
	}
}
{"su100y"
	{on spawn
    	{tags add "spg"}
		{tags add "soviet"}
		{tags add "su100y"}
	}
}
{"su122"
	{on spawn
    	{tags add "spg"}
		{tags add "soviet"}
		{tags add "su122"}
	}
}
{"su152"
	{on spawn
    	{tags add "spg"}
		{tags add "soviet"}
		{tags add "su152"}
	}
}
{"isu122"
	{on spawn
    	{tags add "spg"}
		{tags add "soviet"}
		{tags add "isu122"}
	}
}
{"isu122s"
	{on spawn
    	{tags add "spg"}
		{tags add "soviet"}
		{tags add "isu122s"}
	}
}
{"isu152"
	{on spawn
    	{tags add "spg"}
		{tags add "soviet"}
		{tags add "isu152"}
	}
}

{"wolverine"
	{on spawn
    	{tags add "spg"}
		{tags add "soviet"}
		{tags add "wolverine"}
	}
}

;_______________________________________________
;|					Aircraft					|
;|______________________________________________|

{"conquest_il2"
	{on spawn
    	{tags add "aircraft"}
		{tags add "conquest_il2"}
	}
}

{"il2_mod42" 
	{on spawn
    	{tags add "aircraft"}
	}
}

{"il2_mod42player" 
	{on spawn
    	{tags add "playerplane"}
			{call "takeoff"}
			{call"takeoff_load"}	
	}
}

{"il2_mod42_para_plane" 
	{on spawn
    	{tags add "aircraft"}
    	{tags add "soviet"}
		{tags add "drop_plane"}
		{tags add "ready_to_move"}
	}
}

{"il2_mod42_para_planeplayer" 
	{on spawn
    	{tags add "player_drop_plane"}
    	{tags add "aircraft"}
    	{tags add "soviet"}
    }
}