{"pf508"
	{on spawn
    	{if not tagged "radiorus"
		    {tags add "radio_car"}
		}
		{tags add "polish"}
		{tags add "pf508"}

	}
}


;AUTOMATIC WEAPONRY
{"303_bren_pol"
	{on spawn
	    {tags add "HMG"}
		{tags add "polish"}
		{tags add "303_bren_pol"}

	}
}
{"ckm_wz30_mgun"
	{on spawn
	    {tags add "HMG"}
		{tags add "polish"}
		{tags add "ckm_wz30_mgun"}

	}
}
{"qf40mm_pol"
	{on spawn
	    {tags add "AAFLAK"}
		{tags add "polish"}
		{tags add "qf40mm_pol"}

	}
}
{"qf2pdr_pol"
	{on spawn
	    {tags add "light_at_gun"}
		{tags add "polish"}
		{tags add "qf2pdr_pol"}

	}
}
{"37mm_bofors"
	{on spawn
	    {tags add "light_at_gun"}
		{tags add "polish"}
		{tags add "37mm_bofors"}

	}
}
{"qf6pdr_pol"
	{on spawn
	    {tags add "medium_at_gun"}
		{tags add "polish"}
		{tags add "qf6pdr_pol"}

	}
}
{"qf17pdr_pol"
	{on spawn
	    {tags add "heavy_at_gun"}
		{tags add "polish"}
		{tags add "qf17pdr_pol"}

	}
}

{"20mm_fka"
	{on spawn
	    {tags add "AAFLAK"}
		{tags add "polish"}
		{tags add "20mm_fka"}

	}
}
{"75mm_aa_wz36"
	{on spawn
	    {tags add "heavy_at_gun"}
		{tags add "polish"}
		{tags add "75mm_aa_wz36"}

	}
}

;HOWITZERS
{"81mm_brandt_pol"
	{on spawn
    	{tags add "artillery"}
		{tags add "polish"}
		{tags add "81mm_brandt_pol"}

	
	}
}
{"qf25pdr_pol"
	{on spawn
    	{tags add "artillery"}
		{tags add "polish"}
		{tags add "qf25pdr_pol"}

	}
}
{"bl45_pol"
	{on spawn
    	{tags add "artillery"}
		{tags add "polish"}
		{tags add "bl45_pol"}

	}
}
{"105mm_wz29"
	{on spawn
    	{tags add "artillery"}
		{tags add "polish"}
		{tags add "105mm_wz29"}

	}
}
{"155mm_wz1917"
	{on spawn
    	{tags add "artillery"}
		{tags add "polish"}
		{tags add "155mm_wz1917"}

	}
}
;_________________________________________________
;|               Wheeled vehicles                 |
;|________________________________________________|


{"bedford_ql_inf"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "polish"}
		{tags add "bedford_ql_inf"}

    }
}
{"bedford_ql_art"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "polish"}
		{tags add "bedford_ql_art"}

    }
}
{"bedford_ql_eng"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "polish"}
		{tags add "bedford_ql_eng"}

    }
}
{"dingo_pol"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "polish"}
		{tags add "dingo_pol"}

	}
}
{"m3halftrack_pol"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "polish"}
		{tags add "m3halftrack_pol"}

	}
}
{"staghound_pol"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "polish"}
		{tags add "staghound_pol"}

	}
}
{"wz34"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "polish"}
		{tags add "wz34"}

	}
}
;_________________________________________________
;|        Main Battle Tanks and SPGs              |
;|________________________________________________|

;LIGHT
{"crusader_aa2_pol"
	{on spawn
    	{tags add "light_tank"}
		{tags add "polish"}
		{tags add "crusader_aa2_pol"}

	}
}
{"crusader_pol"
	{on spawn
    	{tags add "light_tank"}
		{tags add "polish"}
		{tags add "crusader_pol"}

	}
}
{"tks-mg"
	{on spawn
    	{tags add "light_tank"}
		{tags add "polish"}
		{tags add "tks-mg"}

	}
}
{"tks-mg"
	{on spawn
    	{tags add "light_tank"}
		{tags add "polish"}
		{tags add "tks-mg"}

	}
}
{"tks-20mm"
	{on spawn
    	{tags add "light_tank"}
		{tags add "polish"}
		{tags add "tks-mg"}

	}
}
{"vickersedw"
	{on spawn
    	{tags add "light_tank"}
		{tags add "polish"}
		{tags add "tks-mg"}

	}
}
{"vickersejw"
	{on spawn
    	{tags add "light_tank"}
		{tags add "polish"}
		{tags add "tks-mg"}

	}
}
{"7tp"
	{on spawn
    	{tags add "light_tank"}
		{tags add "polish"}
		{tags add "tks-mg"}

	}
}
{"r35_pol"
	{on spawn
    	{tags add "light_tank"}
		{tags add "polish"}
		{tags add "tks-mg"}

	}
}

;MEDIUM
{"cromwell_mk_iv_pol"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "polish"}
		{tags add "cromwell_mk_iv_pol"}

	}
}
{"m4a4_pol"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "polish"}
		{tags add "m4a4_pol"}

	}
}
{"challenger_pol"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "polish"}
		{tags add "challenger_pol"}

	}
}
{"m4a4_firefly_pol"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "polish"}
		{tags add "m4a4_firefly_pol"}

	}
}

;SPG
{"achilles_pol"
	{on spawn
    	{tags add "spg"}
		{tags add "polish"}
		{tags add "achilles_pol"}

	}
}
{"m4a3_105_pol"
	{on spawn
    	{tags add "spg"}
		{tags add "polish"}
		{tags add "m4a3_105_pol"}

	}
}
{"sexton_pol"
	{on spawn
    	{tags add "spg"}
		{tags add "polish"}
		{tags add "sexton_pol"}

	}
}
{"pf621_75mm"
	{on spawn
    	{tags add "spg"}
		{tags add "polish"}
		{tags add "pf621_75mm"}

	}
}