{"willys_com"
	{on spawn
    	{if not tagged "radiorus"
		    {tags add "radio_car"}
		}
		{tags add "american"}
		{tags add "willys_com"}

	}
}

;AUTOMATIC WEAPONRY
{"0_3cal_m1917a1_aa"
	{on spawn
	    {tags add "HMG"}
		{tags add "american"}
		{tags add "0_3cal_m1917a1_aa"}

	}
}
{"0_5cal_m2hb"
	{on spawn
	    {tags add "HMG"}
		{tags add "american"}
		{tags add "0_5cal_m2hb"}

	}
}
{"0_5cal_maxson"
	{on spawn
	    {tags add "AAFLAK"}
		{tags add "american"}
		{tags add "0_5cal_maxson"}

	}
}
{"40_mm_m1"
	{on spawn
	    {tags add "AAFLAK"}
		{tags add "american"}
		{tags add "40_mm_m1"}

	}
}


; AT WEAPONRY

{"37_mm_m3"
	{on spawn
	    {tags add "light_at_gun"}
		{tags add "american"}
		{tags add "37_mm_m3"}

	}
}
{"75_mm_m1897a4"
	{on spawn
	    {tags add "light_at_gun"}
		{tags add "american"}
		{tags add "75_mm_m1897a4"}

	}
}
{"76_mm_m5"
	{on spawn
	    {tags add "medium_at_gun"}
		{tags add "american"}
		{tags add "76_mm_m5"}

	}
}
{"76_mm_m5late"
	{on spawn
	    {tags add "medium_at_gun"}
		{tags add "american"}
		{tags add "76_mm_m5late"}

	}
}
{"90_mm_m1"
	{on spawn
	    {tags add "heavy_at_gun"}
		{tags add "american"}
		{tags add "mmm190"}

	}
}

;HOWITZERS
{"75_mm_m1"
	{on spawn
    	{tags add "medium_at_gun"}
		{tags add "american"}
		{tags add "75_mm_m1"}

	}
}
{"81_mm_m1"
	{on spawn
    	{tags add "artillery"}
		{tags add "american"}
		{tags add "81_mm_m1"}

	}
}
{"107_mm_m2"
	{on spawn
    	{tags add "artillery"}
		{tags add "american"}
		{tags add "107_mm_m2"}

	}
}
{"105_mm_m2a1l"
	{on spawn
    	{tags add "artillery"}
		{tags add "american"}
		{tags add "105_mm_m2a1l"}

	}
}
{"155_mm_m2"
	{on spawn
    	{tags add "artillery"}
		{tags add "american"}
		{tags add "155_mm_m2"}

	}
}
{"203_mm_m115"
	{on spawn
    	{tags add "artillery"}
		{tags add "american"}
		{tags add "203_mm_m115"}

	}
}

;_________________________________________________
;|               Wheeled vehicles                 |
;|________________________________________________|


{"cckw353_inf"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "cckw353_inf"}

    }
}
{"cckw353_2xt27"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "cckw353_2xt27"}
		{tags add "rocket_artillery"}

    }
}
{"willysmb"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "willysmb"}

    }
}
{"willys50"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "willys50"}

    }
}
{"cckw353_fuel"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "cckw353_fuel"}

	}
}
{"cckw352_art"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "cckw352_art"}

	}
}
{"cckw353_eng"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "cckw353_eng"}

	}
}
{"m3_usa"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "m3_usa"}

	}
}
{"m3a1_scout"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "m3a1_scout"}

	}
}
{"m20"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "m20"}

	}
}
{"m16"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "m16"}

	}
}
{"dodgewc55"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "dodgewc55"}

	}
}
{"m8_grayhound"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "m8_grayhound"}

	}
}
{"m15a1"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "m15a1"}

	}
}
{"m4halftrack"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "american"}
		{tags add "m4halftrack"}

	}
}

;_________________________________________________
;|        Main Battle Tanks and SPGs              |
;|________________________________________________|

;LIGHT
{"m22"
	{on spawn
    	{tags add "light_tank"}
		{tags add "american"}
		{tags add "m22"}

	}
}
{"m5a1"
	{on spawn
    	{tags add "light_tank"}
		{tags add "american"}
		{tags add "m5a1"}

	}
}
{"m24_chaffee"
	{on spawn
    	{tags add "light_tank"}
		{tags add "american"}
		{tags add "m24_chaffee"}

	}
}
{"m3_satan"
	{on spawn
    	{tags add "light_tank"}
		{tags add "american"}
		{tags add "m8"}

	}
}
{"m3_stuart"
	{on spawn
    	{tags add "light_tank"}
		{tags add "american"}
		{tags add "m8"}

	}
}

;MEDIUM
{"m3lee"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "american"}
		{tags add "m3lee"}

	}
}
{"m4a1"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "american"}
		{tags add "m4a1"}

	}
}
{"m4"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "american"}
		{tags add "m4"}

	}
}
{"m4a3_75"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "american"}
		{tags add "m4a3_75"}

	}
}
{"m4a3_zippo"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "american"}
		{tags add "m4a3_zippo"}

	}
}
{"m4a3e8"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "american"}
		{tags add "m4a3e8"}

	}
}
{"m4a3_105"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "american"}
		{tags add "m4a3_105"}

	}
}
{"m4a3e2_jumbo"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "american"}
		{tags add "m4a3e2_jumbo"}

	}
}
{"m4a3e2_jumbo_76w"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "american"}
		{tags add "m4a3e2_jumbo_76w"}

	}
}

;HEAVY
{"m26_pershing"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "american"}
		{tags add "m26_pershing"}

	}
}
{"m26e4_pershing"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "american"}
		{tags add "m26e4_pershing"}

	}
}

;SPG
{"t12gmc"
	{on spawn
    	{tags add "spg"}
		{tags add "american"}
		{tags add "t12gmc"}

	}
}
{"m10wolverine"
	{on spawn
    	{tags add "spg"}
		{tags add "american"}
		{tags add "m10wolverine"}

	}
}
{"m18"
	{on spawn
    	{tags add "spg"}
		{tags add "american"}
		{tags add "m18"}

	}
}
{"t30hmc"
	{on spawn
    	{tags add "spg"}
		{tags add "american"}
		{tags add "t30hmc"}

	}
}
{"m7"
	{on spawn
    	{tags add "spg"}
		{tags add "american"}
		{tags add "m7"}

	}
}
{"m36"
	{on spawn
    	{tags add "spg"}
		{tags add "american"}
		{tags add "m36"}

	}
}
{"m12gmc"
	{on spawn
    	{tags add "spg"}
		{tags add "american"}
		{tags add "m12gmc"}

	}
}
{"m4a3c"
	{on spawn
    	{tags add "spg"}
		{tags add "american"}
		{tags add "m4a3c"}

	}
}

;_________________________________________________
;|               Aircraft                         |
;|________________________________________________|

{"b25_para_plane"
	{on spawn
		{tags add "usa"}
		{tags add "drop_plane"}	
		{tags add "aircraft"}
		{tags add "ready_to_move"}		
	}
}
