{"laffly_v15t"
	{on spawn
    	{if not tagged "radiorus"
		    {tags add "radio_car"}
		}
		{tags add "french"}
		{tags add "laffly_v15t"}

	}
}

;AUTOMATIC WEAPONRY
{"8mm_breda_37"
	{on spawn
	    {tags add "HMG"}
		{tags add "italian"}
		{tags add "8mm_breda_37"}

	}
}
{"cannone_2065"
	{on spawn
	    {tags add "HMG"}
		{tags add "italian"}
		{tags add "cannone_2065"}

	}
}



; AT WEAPONRY

{"2cm_solothurn"
	{on spawn
	    {tags add "light_at_gun"}
		{tags add "italian"}
		{tags add "2cm_solothurn"}

	}
}
{"cannone_4732"
	{on spawn
	    {tags add "light_at_gun"}
		{tags add "italian"}
		{tags add "cannone_4732"}

	}
}
{"cannone_7527"
	{on spawn
	    {tags add "medium_at_gun"}
		{tags add "italian"}
		{tags add "cannone_7527"}

	}
}
{"7_5cm_pak97_38"
	{on spawn
	    {tags add "heavy_at_gun"}
		{tags add "italian"}
		{tags add "cmpak9738"}

	}
}

;HOWITZERS
{"obice_7513"
	{on spawn
    	{tags add "artillery"}
		{tags add "italian"}
		{tags add "obice_7513"}

	
	}
}
{"81mm_brandt_ita"
	{on spawn
    	{tags add "artillery"}
		{tags add "italian"}
		{tags add "81mm_brandt_ita"}

	}
}
{"obice_10017"
	{on spawn
    	{tags add "artillery"}
		{tags add "italian"}
		{tags add "obice_10017"}

	}
}
{"obice_210"
	{on spawn
    	{tags add "artillery"}
		{tags add "italian"}
		{tags add "obice_210"}

	}
}

;_________________________________________________
;|               Wheeled vehicles                 |
;|________________________________________________|


{"fiat626"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "italian"}
		{tags add "fiat626"}

    }
}
{"fiat626_fuel"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "italian"}
		{tags add "fiat626_fuel"}

    }
}
{"fiat626_inf"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "italian"}
		{tags add "fiat626_inf"}

    }
}
{"fiat626_art"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "italian"}
		{tags add "fiat626_art"}

    }
}
{"fiat626_eng"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "italian"}
		{tags add "fiat626_eng"}

    }
}
{"as42"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "italian"}
		{tags add "as42"}

	}
}
{"ab41"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "italian"}
		{tags add "ab41"}

	}
}
{"autocannone10017"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "italian"}
		{tags add "autocannone10017"}

	}
}

;_________________________________________________
;|        Main Battle Tanks and SPGs              |
;|________________________________________________|

;LIGHT
{"cv35"
	{on spawn
    	{tags add "light_tank"}
		{tags add "italian"}
		{tags add "cv35"}

	}
}
{"l640"
	{on spawn
    	{tags add "light_tank"}
		{tags add "italian"}
		{tags add "l640"}

	}
}


;MEDIUM
{"m1441"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "italian"}
		{tags add "m1441"}

	}
}
{"m1542"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "italian"}
		{tags add "m1542"}

	}
}
{"pz3n_ita"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "italian"}
		{tags add "pz3n_ita"}

	}
}
{"pz4g_ita"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "italian"}
		{tags add "pz4g_ita"}

	}
}

;SPG
{"m7518"
	{on spawn
    	{tags add "spg"}
		{tags add "italian"}
		{tags add "m7518"}

	}
}
{"m7534"
	{on spawn
    	{tags add "spg"}
		{tags add "italian"}
		{tags add "m7534"}

	}
}
{"stug3g_ita"
	{on spawn
    	{tags add "spg"}
		{tags add "italian"}
		{tags add "stug3g_ita"}

	}
}

;_________________________________________________
;|               Aircraft                         |
;|________________________________________________|

{"sm79_para_plane"
	{on spawn
		{tags add "italian"}
		{tags add "german"}
		{tags add "drop_plane"}	
		{tags add "aircraft"}
		{tags add "ready_to_move"}		
	}
}
