{"laffly_v15t"
	{on spawn
    	{if not tagged "radiorus"
		    {tags add "radio_car"}
		}
		{tags add "french"}
		{tags add "laffly_v15t"}
	}
}

;AUTOMATIC WEAPONRY
{"0_3cal_m1919a4_fr"
	{on spawn
	    {tags add "HMG"}
		{tags add "french"}
		{tags add "0_3cal_m1919a4_fr"}

	}
}
{"0_5cal_m2hb_fr"
	{on spawn
	    {tags add "HMG"}
		{tags add "french"}
		{tags add "0_5cal_m2hb_fr"}

	}
}

;AA WEAPONRY
{"13mm_hotchkiss"
	{on spawn
	    {tags add "AAFLAK"}
		{tags add "french"}
		{tags add "13mm_hotchkiss"}

	}
}
{"40_mm_m1_fr"
	{on spawn
	    {tags add "AAFLAK"}
		{tags add "french"}
		{tags add "40_mm_m1_fr"}

	}
}


; AT WEAPONRY

{"25mm_hotchkiss_mle34"
	{on spawn
	    {tags add "light_at_gun"}
		{tags add "french"}
		{tags add "25mm_hotchkiss_mle34"}

	}
}
{"47mm_puteaux_mle37"
	{on spawn
	    {tags add "light_at_gun"}
		{tags add "french"}
		{tags add "47mm_puteaux_mle37"}

	}
}
{"57_mm_m1_fr"
	{on spawn
	    {tags add "medium_at_gun"}
		{tags add "french"}
		{tags add "57_mm_m1_fr"}

	}
}


;HOWITZERS
{"75_mm_m1897a4_fr"
	{on spawn
    	{tags add "medium_at_gun"}
		{tags add "french"}
		{tags add "75_mm_m1897a4_fr"}

	
	}
}
{"81_mm_m1_fr"
	{on spawn
    	{tags add "artillery"}
		{tags add "french"}
		{tags add "81_mm_m1_fr"}

	}
}
{"105_mm_m2a1l_fr"
	{on spawn
    	{tags add "artillery"}
		{tags add "french"}
		{tags add "105_mm_m2a1l_fr"}

	}
}
{"155_mm_m1918"
	{on spawn
    	{tags add "artillery"}
		{tags add "french"}
		{tags add "155_mm_m1918"}

	}
}
{"22cm_mortier"
	{on spawn
    	{tags add "artillery"}
		{tags add "french"}
		{tags add "22cm_mortier"}

	}
}
;_________________________________________________
;|               Wheeled vehicles                 |
;|________________________________________________|


{"cckw352_fr_inf"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "french"}
		{tags add "cckw352_fr_inf"}

    }
}
{"chevrolet_fuel_fr"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "french"}
		{tags add "chevrolet_fuel_fr"}

    }
}
{"cckw352_fr_art"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "french"}
		{tags add "cckw352_fr_art"}

    }
}
{"cckw352_fr_eng"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "french"}
		{tags add "cckw352_fr_eng"}

    }
}
{"m3a1_scout_fr"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "french"}
		{tags add "m3a1_scout_fr"}
	}
}
{"dodgewc55_fr"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "french"}
		{tags add "dodgewc55_fr"}

	}
}
{"m20_fr"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "french"}
		{tags add "m20_fr"}

	}
}
{"m8_grayhound_fr"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "french"}
		{tags add "m8_grayhound_fr"}

	}
}
{"m17_fr"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "french"}
		{tags add "m17_fr"}

	}
}
{"m4halftrack_fr"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "french"}
		{tags add "m4halftrack_fr"}
	}
}
{"laffly_v15t_mg"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "french"}
		{tags add "laffly_v15t_mg"}
	}
}
{"laffly_s15_toe"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "french"}
		{tags add "laffly_s15_toe"}
	}
}
{"autocanon_75mm"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "french"}
		{tags add "autocanon_75mm"}
	}
}
{"panhard"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "french"}
		{tags add "panhard"}
	}
}
;_________________________________________________
;|        Main Battle Tanks and SPGs              |
;|________________________________________________|

;LIGHT
{"m5a1_fr"
	{on spawn
    	{tags add "light_tank"}
		{tags add "french"}
		{tags add "m5a1_fr"}

	}
}
{"m8_fr"
	{on spawn
    	{tags add "light_tank"}
		{tags add "french"}
		{tags add "m8_fr"}

	}
}
{"amr35-13mm"
	{on spawn
    	{tags add "light_tank"}
		{tags add "french"}
		{tags add "amr35-13mm"}

	}
}
{"r35"
	{on spawn
    	{tags add "light_tank"}
		{tags add "french"}
		{tags add "r35"}

	}
}
{"amr35-25mm"
	{on spawn
    	{tags add "light_tank"}
		{tags add "french"}
		{tags add "amr35-25mm"}

	}
}
{"r39"
	{on spawn
    	{tags add "light_tank"}
		{tags add "french"}
		{tags add "r39"}

	}
}
{"h39"
	{on spawn
    	{tags add "light_tank"}
		{tags add "french"}
		{tags add "h39"}

	}
}


;MEDIUM
{"cavalier_mk_vii"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "french"}
		{tags add "cavalier_mk_vii"}

	}
}
{"m4a3_75_fr"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "french"}
		{tags add "m4a3_75_fr"}

	}
}
{"m4a3_76_fr"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "french"}
		{tags add "m4a3_76_fr"}

	}
}
{"char_d2"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "french"}
		{tags add "char_d2"}

	}
}
{"s35"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "french"}
		{tags add "s35"}

	}
}
{"b1bis"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "french"}
		{tags add "b1bis"}

	}
}

;SPG
{"m10wolverine_fr"
	{on spawn
    	{tags add "spg"}
		{tags add "french"}
		{tags add "m10wolverine_fr"}

	}
}
{"m4a3_105_fr"
	{on spawn
    	{tags add "spg"}
		{tags add "french"}
		{tags add "m4a3_105_fr"}

	}
}
{"m7_fr"
	{on spawn
    	{tags add "spg"}
		{tags add "french"}
		{tags add "m7_fr"}

	}
}
{"laffly15tcc"
	{on spawn
    	{tags add "spg"}
		{tags add "french"}
		{tags add "laffly15tcc"}

	}
}
{"bs-75"
	{on spawn
    	{tags add "spg"}
		{tags add "french"}
		{tags add "bs-75"}

	}
}