{"type95_com"
	{on spawn
    	{if not tagged "radiorus"
		    {tags add "radio_car"}
		}
		{tags add "japanese"}
		{tags add "type95_com"}

	}
}

;AUTOMATIC WEAPONRY
{"type92_stan"
	{on spawn
	    {tags add "HMG"}
		{tags add "japanese"}
		{tags add "type92_stan"}

	}
}
{"20mm_type_2"
	{on spawn
	    {tags add "AAFLAK"}
		{tags add "japanese"}
		{tags add "20mm_type_2"}

	}
}

; AT WEAPONRY
{"37mm_type_94"
	{on spawn
	    {tags add "light_at_gun"}
		{tags add "japanese"}
		{tags add "37mm_type_94"}

	}
}
{"47mm_type_1"
	{on spawn
	    {tags add "light_at_gun"}
		{tags add "japanese"}
		{tags add "47mm_type_1"}

	}
}
{"75mm_type_88"
	{on spawn
	    {tags add "medium_at_gun"}
		{tags add "japanese"}
		{tags add "75mm_type_88"}

	}
}
{"75mm_type_90"
	{on spawn
	    {tags add "medium_at_gun"}
		{tags add "japanese"}
		{tags add "75mm_type_90"}

	}
}
{"75mm_type_4"
	{on spawn
	    {tags add "medium_at_gun"}
		{tags add "japanese"}
		{tags add "75mm_type_4"}

	}
}

;HOWITZERS
{"75mm_type_41"
	{on spawn
    	{tags add "medium_at_gun"}
		{tags add "japanese"}
		{tags add "75mm_type_41"}

	
	}
}
{"81mm_brandt_jap"
	{on spawn
    	{tags add "artillery"}
		{tags add "japanese"}
		{tags add "81mm_brandt_jap"}

	}
}
{"150mm_type_97"
	{on spawn
    	{tags add "artillery"}
		{tags add "japanese"}
		{tags add "150mm_type_97"}

	}
}
{"150mm_type_96"
	{on spawn
    	{tags add "artillery"}
		{tags add "japanese"}
		{tags add "150mm_type_96"}

	}
}
{"200mm_type_4"
	{on spawn
    	{tags add "rocket_artillery"}
		{tags add "japanese"}
		{tags add "200mm_type_4"}

	}
}
{"type4_ha-to"
	{on spawn
    	{tags add "rocket_artillery"}
		{tags add "japanese"}
		{tags add "type4_ha-to"}

	}
}
{"105mm_type_92"
	{on spawn
    	{tags add "artillery"}
		{tags add "japanese"}
		{tags add "105mm_type_92"}

	}
}
{"120mm_type_38"
	{on spawn
    	{tags add "heavy_at_gun"}
		{tags add "japanese"}
		{tags add "120mm_type_38"}

	}
}

;_________________________________________________
;|               Wheeled vehicles                 |
;|________________________________________________|


{"type94"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "japanese"}
		{tags add "type94"}

    }
}
{"type95"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "japanese"}
		{tags add "type95"}

    }
}
{"type94art"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "japanese"}
		{tags add "type94art"}

    }
}
{"type94eng"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "japanese"}
		{tags add "type94eng"}

	}
}
{"type94inf"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "japanese"}
		{tags add "type94inf"}

    }
}
{"type94_fuel"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "japanese"}
		{tags add "type94_fuel"}

    }
}
{"type1_ho-ki_mg"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "japanese"}
		{tags add "type1_ho-ki_mg"}

	}
}
{"type87"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "japanese"}
		{tags add "type87"}

	}
}
{"type93"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "japanese"}
		{tags add "type93"}

	}
}
{"type94aa"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "japanese"}
		{tags add "type94aa"}

	}
}
{"toyota_rocket"
	{on spawn
    		{tags add "wheeled_vehicle"}
		{tags add "rocket_artillery"}
		{tags add "japanese"}
		{tags add "toyota_rocket"}

	}
}

;_________________________________________________
;|        Main Battle Tanks and SPGs              |
;|________________________________________________|

;LIGHT
{"type94_te-ke"
	{on spawn
    	{tags add "light_tank"}
		{tags add "japanese"}
		{tags add "type94_te-ke"}

	}
}
{"type97_te-ke"
	{on spawn
    	{tags add "light_tank"}
		{tags add "japanese"}
		{tags add "type97_te-ke"}

	}
}
{"type95_ha-go"
	{on spawn
    	{tags add "light_tank"}
		{tags add "japanese"}
		{tags add "type95_ha-go"}

	}
}

;MEDIUM
{"type97_chi-ha"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "japanese"}
		{tags add "type97_chi-ha"}

	}
}
{"type97_shinhoto_47mm"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "japanese"}
		{tags add "type97_shinhoto_47mm"}

	}
}
{"type1_chi-he"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "japanese"}
		{tags add "type1_chi-he"}

	}
}
{"type97_shinhoto_120mm"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "japanese"}
		{tags add "type97_shinhoto_120mm"}

	}
}
{"type2_ho-i_kou"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "japanese"}
		{tags add "type2_ho-i_kou"}

	}
}
{"type3_chi-nu"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "japanese"}
		{tags add "type3_chi-nu"}

	}
}
{"type3_chi-nu2"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "japanese"}
		{tags add "type3_chi-nu2"}

	}
}
{"type2_ho-i"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "japanese"}
		{tags add "type2_ho-i"}

	}
}

;SPG
{"type1_ho-ni1"
	{on spawn
    	{tags add "spg"}
		{tags add "japanese"}
		{tags add "type1_ho-ni1"}

	}
}
{"type1_ho-ni2"
	{on spawn
    	{tags add "spg"}
		{tags add "japanese"}
		{tags add "type1_ho-ni2"}

	}
}
{"type4_ho-ro"
	{on spawn
    	{tags add "spg"}
		{tags add "japanese"}
		{tags add "type4_ho-ro"}

	}
}
{"type5_ho-chi"
	{on spawn
    	{tags add "spg"}
		{tags add "japanese"}
		{tags add "type5_ho-chi"}

	}
}
;_________________________________________________
;|               Aircraft                         |
;|________________________________________________|

{"j2m_raiden_para_plane"
	{on spawn
		{tags add "japanese"}
		{tags add "drop_plane"}	
		{tags add "aircraft"}
		{tags add "ready_to_move"}		
	}
}
