{"morris_cs8"
	{on spawn
    	{if not tagged "radiorus"
		    {tags add "radio_car"}
		}
		{tags add "english"}
		{tags add "morris_cs8"}

	}
}
{"303_bren"
	{on spawn
	    {tags add "HMG"}
		{tags add "english"}
		{tags add "303_bren"}
	}
}
{"qf40mm"
	{on spawn
	    {tags add "AAFLAK"}
		{tags add "english"}
		{tags add "qf40mm"}
	}
}
{"qf3,7inch"
	{on spawn
	    {tags add "AAFLAK"}
		{tags add "english"}
		{tags add "qf3,7inch"}
	}
}

; AT WEAPONRY
{"qf2pdr"
	{on spawn
	    {tags add "light_at_gun"}
		{tags add "english"}
		{tags add "qf2pdr"}

	}
}
{"qf6pdr"
	{on spawn
	    {tags add "medium_at_gun"}
		{tags add "english"}
		{tags add "qf6pdr"}

	}
}
{"qf17pdr"
	{on spawn
	    {tags add "heavy_at_gun"}
		{tags add "english"}
		{tags add "qf17pdr"}

	}
}


;HOWITZERS
{"76mm_mk_ii"
	{on spawn
    	{tags add "artillery"}
		{tags add "english"}
		{tags add "76mm_mk_ii"}

	
	}
}
{"qf25pdr"
	{on spawn
    	{tags add "artillery"}
		{tags add "english"}
		{tags add "qf25pdr"}

	}
}
{"bl45"
	{on spawn
    	{tags add "artillery"}
		{tags add "english"}
		{tags add "bl45"}

	}
}
{"bl72"
	{on spawn
    	{tags add "artillery"}
		{tags add "english"}
		{tags add "bl72"}

	}
}
{"land_mattress"
	{on spawn
    		{tags add "rocket_artillery"}
		{tags add "english"}
		{tags add "land_mattress"}

	}
}
;_________________________________________________
;|               Wheeled vehicles                 |
;|________________________________________________|


{"matador"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "english"}
		{tags add "matador"}

    }
}
{"matador_art"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "english"}
		{tags add "matador_art"}

    }
}
{"matador_eng"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "english"}
		{tags add "matador_eng"}

    }
}
{"matador_fuel"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "english"}
		{tags add "matador_fuel"}

    }
}
{"dingo"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "english"}
		{tags add "dingo"}
	}
}
{"m3halftrack_eng"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "english"}
		{tags add "m3halftrack_eng"}
	}
}
{"humber"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "english"}
		{tags add "humber"}
	}
}
{"mk2daimler"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "english"}
		{tags add "mk2daimler"}
	}
}
{"staghound"
	{on spawn
    	{tags add "wheeled_vehicle"}
		{tags add "english"}
		{tags add "staghound"}

	}
}

;_________________________________________________
;|        Main Battle Tanks and SPGs              |
;|________________________________________________|

;LIGHT
{"crusader_aa1"
	{on spawn
    	{tags add "light_tank"}
		{tags add "english"}
		{tags add "crusader_aa1"}

	}
}
{"crusader_aa2"
	{on spawn
    	{tags add "light_tank"}
		{tags add "english"}
		{tags add "crusader_aa2"}

	}
}
{"crusader_mk6"
	{on spawn
    	{tags add "light_tank"}
		{tags add "english"}
		{tags add "crusader_mk6"}

	}
}
{"crusader_mki"
	{on spawn
    	{tags add "light_tank"}
		{tags add "english"}
		{tags add "crusader_mk6"}

	}
}
{"crusader_mki_cs"
	{on spawn
    	{tags add "light_tank"}
		{tags add "english"}
		{tags add "crusader_mk6"}

	}
}

;MEDIUM
{"valentine_mkiii"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "english"}
		{tags add "valentine_mkiii"}

	}
}
{"matilda_mkii"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "english"}
		{tags add "matilda_mkii"}

	}
}
{"matilda_mkii_cs"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "english"}
		{tags add "matilda_mkii_cs"}

	}
}
{"cromwell_mk_iv"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "english"}
		{tags add "cromwell_mk_iv"}

	}
}
{"m4a4"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "english"}
		{tags add "m4a4"}

	}
}
{"cromwell_mk_vi"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "english"}
		{tags add "cromwell_mk_vi"}

	}
}
{"comet_a34"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "english"}
		{tags add "comet_a34"}

	}
}
{"challenger_a30"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "english"}
		{tags add "challenger_a30"}

	}
}
{"m4a4_firefly"
	{on spawn
    	{tags add "medium_tank"}
		{tags add "english"}
		{tags add "m4a4_firefly"}

	}
}


;HEAVY
{"churchill3"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "english"}
		{tags add "churchill3"}

	}
}
{"churchill_mk_ii"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "english"}
		{tags add "churchill_mk_ii"}

	}
}
{"churchill_avre"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "english"}
		{tags add "churchill_avre"}

	}
}
{"churchill_mk_iv"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "english"}
		{tags add "churchill_mk_iv"}

	}
}
{"churchill_mk_vii"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "english"}
		{tags add "churchill_mk_vii"}

	}
}
{"churchill_crocodile"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "english"}
		{tags add "churchill_crocodile"}

	}
}
{"black_prince"
	{on spawn
    	{tags add "heavy_tank"}
		{tags add "english"}
		{tags add "black_prince"}

	}
}


;SPG
{"achilles"
	{on spawn
    	{tags add "spg"}
		{tags add "english"}
		{tags add "achilles"}

	}
}
{"m4a3_105_eng"
	{on spawn
    	{tags add "spg"}
		{tags add "english"}
		{tags add "m4a3_105_eng"}

	}
}
{"sexton"
	{on spawn
    	{tags add "spg"}
		{tags add "english"}
		{tags add "sexton"}

	}
}

;_________________________________________________
;|               Aircraft                         |
;|________________________________________________|

{"beaufighter_para_plane"
	{on spawn
		{tags add "english"}
		{tags add "drop_plane"}	
		{tags add "aircraft"}
		{tags add "ready_to_move"}
	}
}



