	{Human "" 0x8001
		{Position -2932.92 -32936.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 2}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8002
		{Position -2858.79 -32877.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 3}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8003
		{Position -2926.65 -32877.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 4}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8004
		{Position -2874.36 -32821.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 5}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8005
		{Position -2918.94 -32820.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 6}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8006
		{Position -2855.1 -32761.1}
		{xform zl 50.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 7}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8007
		{Position -2917.44 -32763.2}
		{xform zl 5.99}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 8}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8008
		{Position -3008.17 -32932}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 9}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8009
		{Position -3073.69 -32931.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 10}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x800a
		{Position -2999.91 -32872}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 11}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x800b
		{Position -3065.75 -32872}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 12}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x800d
		{Position -3083.48 -32816.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 14}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x800e
		{Position -2996.14 -32759}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 15}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x800f
		{Position -3061.36 -32759.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 16}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8010
		{Position -2882.35 -32691.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 17}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8011
		{Position -2943.53 -32692.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 18}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8012
		{Position -2851.25 -32635.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 19}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8013
		{Position -2916.25 -32636.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 20}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8029
		{Position -3346.1 -32920.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 42}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x802a
		{Position -3268.39 -32860.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 43}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x802b
		{Position -3337.29 -32865.8}
		{xform zl -39}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 44}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x802c
		{Position -3266.9 -32803.7}
		{xform zl 34.75}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 45}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x802d
		{Position -3355.09 -32804.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 46}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x802e
		{Position -3291.52 -32746.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 47}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x802f
		{Position -3332 -32744.6}
		{xform zl 40.78}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 48}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8030
		{Position -3150.02 -32682.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 49}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8031
		{Position -3192.43 -32683.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 50}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8032
		{Position -3124.83 -32625.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 51}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8033
		{Position -3191.96 -32626.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 52}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8034
		{Position -3150.17 -32570.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 53}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8035
		{Position -3217.05 -32569}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 54}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8036
		{Position -3123.2 -32512}
		{xform zl 22.85}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 55}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8037
		{Position -3190.14 -32513.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 56}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8038
		{Position -3291.11 -32677.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 57}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8039
		{Position -3356.38 -32677.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 58}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x803a
		{Position -3263.94 -32620.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 59}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x803b
		{Position -3330.17 -32615.1}
		{xform zl 39}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 60}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8051
		{Position -3452.46 -32682.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 82}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8052
		{Position -3384.54 -32623.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 83}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8053
		{Position -3451.74 -32622.7}
		{xform zl 44.29}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 84}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8054
		{Position -3411.08 -32567.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 85}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8055
		{Position -3477.11 -32568.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 86}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8056
		{Position -3383.78 -32512.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 87}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8057
		{Position -3448.04 -32509.1}
		{xform zl 42.52}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 88}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8058
		{Position -3551.56 -32676.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 89}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8059
		{Position -3617.57 -32676.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 90}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x805a
		{Position -3526.37 -32617.7}
		{xform zl 35.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 91}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x805b
		{Position -3592.46 -32619.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 92}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x805c
		{Position -3551.86 -32564.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 93}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x805d
		{Position -3617.94 -32564.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 94}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x805e
		{Position -3524.02 -32506.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 95}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x805f
		{Position -3591.11 -32507.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 96}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8060
		{Position -3671.97 -32913.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 97}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8061
		{Position -3737.67 -32913.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 98}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8062
		{Position -3663.71 -32854.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 99}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8063
		{Position -3729.5 -32853.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 100}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8064
		{Position -3681.32 -32798.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 101}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8078
		{Position -3823.52 -32665.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 121}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8079
		{Position -3889.53 -32664.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 122}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x807a
		{Position -3798.65 -32608.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 123}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x807b
		{Position -3864.54 -32608.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 124}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x807c
		{Position -3823.7 -32553.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 125}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x807d
		{Position -3889.67 -32553.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 126}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x807e
		{Position -3797.23 -32497}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 127}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x807f
		{Position -3863.27 -32496.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 128}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc000
		{Position -3933.7 -32908.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 257}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc001
		{Position -4000.22 -32908.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 258}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc002
		{Position -3925.97 -32848.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 259}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc003
		{Position -3991.85 -32848.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 260}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc004
		{Position -3943.5 -32792.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 261}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc005
		{Position -4009.52 -32792.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 262}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc006
		{Position -3921.35 -32736}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 263}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc007
		{Position -3988.69 -32736.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 264}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc008
		{Position -3943.06 -32664.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 265}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc009
		{Position -3981.17 -32662.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 266}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc00a
		{Position -3920.16 -32607.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 267}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xc00b
		{Position -3980.77 -32606.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 268}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x808a
		{Position -2723.85 -32652.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 139}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x808b
		{Position -2788.01 -32651.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 140}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x808c
		{Position -2715.54 -32593.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 141}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x808d
		{Position -2784.94 -32594.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 142}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x808e
		{Position -2744.63 -32530.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 143}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x808f
		{Position -2823.74 -32532.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 144}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8097
		{Position -2803.84 -32836}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 146}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8098
		{Position -2729.75 -32776.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 147}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8099
		{Position -2795.68 -32776.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 148}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x809c
		{Position -2867.06 -32936.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 151}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80b1
		{Position -2943.99 -32581.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 172}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80b2
		{Position -2849.05 -32519.4}
		{xform zl 54}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 173}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80b3
		{Position -2915.57 -32524.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 174}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80b4
		{Position -3025.03 -32685.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 175}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80b5
		{Position -3084.73 -32688.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 176}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80b6
		{Position -2993.84 -32631.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 177}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80b7
		{Position -3059.92 -32631.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 178}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80b8
		{Position -3025.85 -32573.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 179}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80b9
		{Position -3084.94 -32576}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 180}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80ba
		{Position -2992.35 -32520.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 181}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80bb
		{Position -3058.41 -32519.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 182}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80bc
		{Position -3138.86 -32925.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 183}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80bd
		{Position -3204.94 -32925.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 184}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80be
		{Position -3130.74 -32866.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 185}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80bf
		{Position -3196.83 -32866}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 186}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80c0
		{Position -3148.63 -32810.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 187}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80c1
		{Position -3214.81 -32805.5}
		{xform zl 54.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 188}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80c2
		{Position -3126.57 -32753.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 189}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80c3
		{Position -3216.07 -32752.3}
		{xform zl 52.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 190}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80d9
		{Position -3356.93 -32568.2}
		{xform zl -54.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 212}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80da
		{Position -3263.05 -32504.9}
		{xform zl 53.19}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 213}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80db
		{Position -3329.06 -32509.8}
		{xform zl -15.22}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 214}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80dc
		{Position -3399.48 -32924.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 215}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80dd
		{Position -3465.53 -32924.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 216}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80de
		{Position -3391.38 -32865.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 217}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80df
		{Position -3457.52 -32864.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 218}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80e0
		{Position -3409.09 -32809.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 219}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80e1
		{Position -3475.25 -32808.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 220}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80e2
		{Position -3387.02 -32752.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 221}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80e3
		{Position -3476 -32751.6}
		{xform zl 52.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 222}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80e4
		{Position -3540.78 -32919.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 223}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80e5
		{Position -3606.55 -32919.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 224}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80e6
		{Position -3532.34 -32860.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 225}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80e7
		{Position -3598.52 -32860.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 226}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80e8
		{Position -3550.19 -32804.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 227}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80e9
		{Position -3616.24 -32804.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 228}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80ea
		{Position -3528.04 -32747.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 229}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x80eb
		{Position -3594.01 -32747.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 230}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8101
		{Position -3747.18 -32798.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 252}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8103
		{Position -3748.39 -32740.8}
		{xform zl 52.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 254}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8104
		{Position -3812.65 -32908.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 255}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8105
		{Position -3878.7 -32908.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 256}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8106
		{Position -3804.49 -32849.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 279}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8107
		{Position -3870.88 -32848.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 280}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8108
		{Position -3822.13 -32793.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 281}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8109
		{Position -3888.36 -32793}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 282}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x810a
		{Position -3800.29 -32736.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 283}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x810b
		{Position -3866.17 -32736.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 284}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x810c
		{Position -3682.56 -32670}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 285}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x810d
		{Position -3725.94 -32671.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 286}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x810e
		{Position -3651.51 -32608}
		{xform zl 53.44}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 287}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x810f
		{Position -3718.2 -32612.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 288}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8110
		{Position -3682.88 -32558}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 289}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8111
		{Position -3749.08 -32562.9}
		{xform zl -85.79}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 290}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8112
		{Position -3651.04 -32501.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 291}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8113
		{Position -3717.63 -32497.2}
		{xform zl 33.72}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 292}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8129
		{Position -4010.93 -32552.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 314}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x812a
		{Position -3917.65 -32495.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 315}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x812b
		{Position -3979.97 -32495}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 316}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x812c
		{Position -2748.67 -32941.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 317}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x812d
		{Position -2814.76 -32941.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 318}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x812e
		{Position -2740.49 -32882.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 319}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x812f
		{Position -2806.49 -32882}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 320}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8130
		{Position -2726.26 -32714.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 321}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8131
		{Position -2792.36 -32714.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 322}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8132
		{Position -4129.73 -32696.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 323}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8133
		{Position -4132.48 -32650.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 324}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8134
		{Position -4110.81 -32611.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 325}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8135
		{Position -4110.31 -32572.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 326}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8136
		{Position -4121.93 -32735.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 327}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8137
		{Position -4186.71 -32698.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 328}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8138
		{Position -4189.58 -32653.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 329}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x8139
		{Position -4167.87 -32613}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 330}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x813a
		{Position -4167.35 -32574.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 331}
		{FsmState "stand_noaim"}
	}
	{Human "" 0x813b
		{Position -4179.41 -32737.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 332}
		{FsmState "stand_noaim"}
	}
	{Human "mp/ger/late/pilot" 0x813c
		{Position -4623.73 -34672.6}
		{xform zl 180 y 12.57 zw -89.51}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 333}
		{NameId 90 55}
		{LastItem "luger"}
	}
	{Human "mp/ger/late/pilot" 0x813d
		{Position -4623.43 -34707.9}
		{xform y 12.57 zw -89.51}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 334}
		{NameId 125 128}
		{LastItem "luger"}
	}
	{Human "mp/rus/late/pilot" 0x813e
		{Position -4198.22 -34703.6}
		{xform zl -178.32 y 11.46 zw -90.88}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 335}
		{NameId 60 70}
		{LastItem "tt33"}
	}
	{Human "mp/fin/late/tank_commander" 0x813f
		{Position -3717.58 -34678.3}
		{xform zl 180 y 11.01 zw -89.3}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 336}
		{Able "-personage"}
		{NameId 23 7}
		{LastItem "lahti_l35"}
	}
	{Human "mp/fin/late/tank_commander" 0x8140
		{Position -3721.61 -34765}
		{xform y 11.01 zw -89.3}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 337}
		{Able "-personage"}
		{NameId 2 58}
		{LastItem "lahti_l35"}
	}
	{Entity "bf110_e2" 0x8141
		{Position -4623.26 -34714}
		{xform zl 180 y 12.57 zw -89.51}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}{nowounddecal 0}}
		}
		{Volume "spin2"
			{able {contact 1}{contact_ground 1}{touch 1}{nowounddecal 0}}
		}
		{DisableObstacles}
		{Player 0}
		{MID 338}
		{Weaponry
			{Current "bomb1"}
		}
		{Chassis "airborne"
			{FuelBag
				{Remain 0}
			}
			{AirborneMode 1}
			{Altitude 47}
		}
	}
	{Entity "il2_mod42" 0x8142
		{Position -4196.35 -34691.7}
		{xform zl -178.32 y 11.46 zw -90.88}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}{nowounddecal 0}}
		}
		{DisableObstacles}
		{Player 0}
		{MID 339}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "bomb1"}
		}
		{Chassis "airborne"
			{FuelBag
				{Remain 0}
			}
			{AirborneMode 1}
			{Altitude 47}
		}
	}
	{Entity "blenheim_mk1" 0x8143
		{Position -3721.99 -34723.7}
		{xform zl 180 y 11.01 zw -89.3}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "2blade3"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}{nowounddecal 0}}
		}
		{Volume "spin2"
			{able {contact 1}{contact_ground 1}{touch 1}{nowounddecal 0}}
		}
		{Discovered 0}
		{DisableObstacles}
		{Player 0}
		{MID 340}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "bomb1"}
		}
		{Chassis "airborne"
			{FuelBag
				{Remain 0}
			}
			{AirborneMode 1}
			{Altitude 47}
		}
	}
	{Human "" 0x814a
		{Position -2737.49 -32836.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 347}
		{FsmState "stand_noaim"}
	}
	{Entity "p47_d22" 0x814e
		{Position -3275.73 -34762}
		{xform zl -84.66 y 9.67 zw 172.68}
		{Volume "1blade1"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "1blade2"
			{able {bullet 0}{contact 0}{blast 0}{touch 0}{nowounddecal 0}}
		}
		{Volume "spin1"
			{able {contact 1}{contact_ground 1}{touch 1}}
		}
		{Player 0}
		{MID 351}
		{Chassis "airborne"
			{AirborneMode 2}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Human "mp/usa/mid/pilot" 0x814f
		{Position -3280.85 -34759.4}
		{xform zl -107.94 y 10.13 zw -163.7}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 352}
		{NameId 14 17}
		{LastItem "m1911"}
	}
	{Human "" 0xa000
		{Position -2942.92 -32946.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 1}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa001
		{Position -2868.79 -32887.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 13}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa002
		{Position -2936.65 -32887.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 21}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa003
		{Position -2884.36 -32831.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 22}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa004
		{Position -2928.94 -32830.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 23}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa005
		{Position -2865.1 -32771.1}
		{xform zl 50.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 24}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa006
		{Position -2927.44 -32773.2}
		{xform zl 5.98}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 25}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa007
		{Position -3018.17 -32942}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 26}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa008
		{Position -3083.69 -32941.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 27}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa009
		{Position -3009.91 -32882}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 28}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa00a
		{Position -3075.75 -32882}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 29}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa00b
		{Position -3093.48 -32826.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 30}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa00c
		{Position -3006.14 -32769}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 31}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa00d
		{Position -3071.36 -32769.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 32}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa00e
		{Position -2892.35 -32701.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 33}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa00f
		{Position -2953.53 -32702.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 34}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa010
		{Position -2861.25 -32645.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 35}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa011
		{Position -2926.25 -32646.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 36}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa012
		{Position -3356.1 -32930.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 37}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa013
		{Position -3278.39 -32870.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 38}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa014
		{Position -3347.29 -32875.8}
		{xform zl -39}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 39}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa015
		{Position -3276.9 -32813.7}
		{xform zl 34.75}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 40}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa016
		{Position -3365.09 -32814.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 41}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa017
		{Position -3301.52 -32756.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 61}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa018
		{Position -3342 -32754.6}
		{xform zl 40.77}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 62}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa019
		{Position -3160.02 -32692.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 63}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa01a
		{Position -3202.43 -32693.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 64}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa01b
		{Position -3134.83 -32635.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 65}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa01c
		{Position -3201.96 -32636.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 66}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa01d
		{Position -3160.17 -32580.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 67}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa01e
		{Position -3227.05 -32579}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 68}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa01f
		{Position -3133.2 -32522}
		{xform zl 22.84}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 69}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa020
		{Position -3200.14 -32523.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 70}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa021
		{Position -3301.11 -32687.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 71}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa022
		{Position -3366.38 -32687.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 72}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa023
		{Position -3273.94 -32630.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 73}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa024
		{Position -3340.17 -32625.1}
		{xform zl 39}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 74}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa025
		{Position -3462.46 -32692.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 75}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa026
		{Position -3394.54 -32633.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 76}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa027
		{Position -3461.74 -32632.7}
		{xform zl 44.27}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 77}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa028
		{Position -3421.08 -32577.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 78}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa029
		{Position -3487.11 -32578.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 79}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa02a
		{Position -3393.78 -32522.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 80}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa02b
		{Position -3458.04 -32519.1}
		{xform zl 42.52}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 81}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa02c
		{Position -3561.56 -32686.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 102}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa02d
		{Position -3627.57 -32686.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 103}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa02e
		{Position -3536.37 -32627.7}
		{xform zl 35.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 104}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa02f
		{Position -3602.46 -32629.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 105}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa030
		{Position -3561.86 -32574.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 106}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa031
		{Position -3627.94 -32574.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 107}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa032
		{Position -3534.02 -32516.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 108}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa033
		{Position -3601.11 -32517.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 109}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa034
		{Position -3681.97 -32923.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 110}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa035
		{Position -3747.67 -32923.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 111}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa036
		{Position -3673.71 -32864.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 112}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa037
		{Position -3739.5 -32863.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 113}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa038
		{Position -3691.32 -32808.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 114}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa039
		{Position -3833.52 -32675.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 115}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa03a
		{Position -3899.53 -32674.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 116}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa03b
		{Position -3808.65 -32618.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 117}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa03c
		{Position -3874.54 -32618.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 118}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa03d
		{Position -3833.7 -32563.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 119}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa03e
		{Position -3899.67 -32563.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 120}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa03f
		{Position -3807.23 -32507}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 129}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa040
		{Position -3873.27 -32506.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 130}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa041
		{Position -3943.7 -32918.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 131}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa042
		{Position -4010.22 -32918.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 132}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa043
		{Position -3935.97 -32858.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 133}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa044
		{Position -4001.85 -32858.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 134}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa045
		{Position -3953.5 -32802.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 135}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa046
		{Position -4019.52 -32802.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 136}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa047
		{Position -3931.35 -32746}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 137}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa048
		{Position -3998.69 -32746.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 138}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa049
		{Position -3953.06 -32674.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 145}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa04a
		{Position -3991.17 -32672.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 152}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa04b
		{Position -3930.16 -32617.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 153}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa04c
		{Position -3990.77 -32616.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 154}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa04d
		{Position -2733.85 -32662.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 155}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa04e
		{Position -2798.01 -32661.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 156}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa04f
		{Position -2725.54 -32603.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 157}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa050
		{Position -2794.94 -32604.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 158}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa051
		{Position -2754.63 -32540.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 159}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa052
		{Position -2833.74 -32542.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 160}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa053
		{Position -2813.84 -32846}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 161}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa054
		{Position -2739.75 -32786.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 162}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa055
		{Position -2805.68 -32786.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 163}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa056
		{Position -2877.06 -32946.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 164}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa057
		{Position -2953.99 -32591.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 165}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa058
		{Position -2859.05 -32529.4}
		{xform zl 53.99}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 166}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa059
		{Position -2925.57 -32534.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 167}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa05a
		{Position -3035.03 -32695.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 168}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa05b
		{Position -3094.73 -32698.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 169}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa05c
		{Position -3003.84 -32641.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 170}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa05d
		{Position -3069.92 -32641.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 171}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa05e
		{Position -3035.85 -32583.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 191}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa05f
		{Position -3094.94 -32586}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 192}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa060
		{Position -3002.35 -32530.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 193}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa061
		{Position -3068.41 -32529.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 194}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa062
		{Position -3148.86 -32935.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 195}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa063
		{Position -3214.94 -32935.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 196}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa064
		{Position -3140.74 -32876.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 197}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa065
		{Position -3206.83 -32876}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 198}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa066
		{Position -3158.63 -32820.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 199}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa067
		{Position -3224.81 -32815.5}
		{xform zl 54.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 200}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa068
		{Position -3136.57 -32763.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 201}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa069
		{Position -3226.07 -32762.3}
		{xform zl 52.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 202}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa06a
		{Position -3366.93 -32578.2}
		{xform zl -54.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 203}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa06b
		{Position -3273.05 -32514.9}
		{xform zl 53.19}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 204}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa06c
		{Position -3339.06 -32519.8}
		{xform zl -15.21}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 205}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa06d
		{Position -3409.48 -32934.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 206}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa06e
		{Position -3475.53 -32934.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 207}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa06f
		{Position -3401.38 -32875.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 208}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa070
		{Position -3467.52 -32874.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 209}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa071
		{Position -3419.09 -32819.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 210}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa072
		{Position -3485.25 -32818.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 211}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa073
		{Position -3397.02 -32762.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 231}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa074
		{Position -3486 -32761.6}
		{xform zl 52.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 232}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa075
		{Position -3550.78 -32929.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 233}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa076
		{Position -3616.55 -32929.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 234}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa077
		{Position -3542.34 -32870.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 235}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa078
		{Position -3608.52 -32870.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 236}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa079
		{Position -3560.19 -32814.3}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 237}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa07a
		{Position -3626.24 -32814.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 238}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa07b
		{Position -3538.04 -32757.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 239}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa07c
		{Position -3604.01 -32757.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 240}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa07d
		{Position -3757.18 -32808.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 241}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa07e
		{Position -3758.39 -32750.8}
		{xform zl 52.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 242}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa07f
		{Position -3822.65 -32918.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 243}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa080
		{Position -3888.7 -32918.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 244}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa081
		{Position -3814.49 -32859.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 245}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa082
		{Position -3880.88 -32858.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 246}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa083
		{Position -3832.13 -32803.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 247}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa084
		{Position -3898.36 -32803}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 248}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa085
		{Position -3810.29 -32746.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 249}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa086
		{Position -3876.17 -32746.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 250}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa087
		{Position -3692.56 -32680}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 251}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa088
		{Position -3735.94 -32681.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 253}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa089
		{Position -3661.51 -32618}
		{xform zl 53.44}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 269}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa08a
		{Position -3728.2 -32622.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 270}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa08b
		{Position -3692.88 -32568}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 271}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa08c
		{Position -3759.08 -32572.9}
		{xform zl -85.79}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 272}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa08d
		{Position -3661.04 -32511.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 273}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa08e
		{Position -3727.63 -32507.2}
		{xform zl 33.72}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 274}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa08f
		{Position -4020.93 -32562.5}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 275}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa090
		{Position -3927.65 -32505.7}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 276}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa091
		{Position -3989.97 -32505}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 277}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa092
		{Position -2758.67 -32951.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 278}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa093
		{Position -2824.76 -32951.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 293}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa094
		{Position -2750.49 -32892.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 294}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa095
		{Position -2816.49 -32892}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 295}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa096
		{Position -2736.26 -32724.8}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 296}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa097
		{Position -2802.36 -32724.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 297}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa098
		{Position -4139.73 -32706.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 298}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa099
		{Position -4142.48 -32660.9}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 299}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa09a
		{Position -4120.81 -32621.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 300}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa09b
		{Position -4120.31 -32582.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 301}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa09c
		{Position -4131.93 -32745.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 302}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa09d
		{Position -4196.71 -32708.4}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 303}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa09e
		{Position -4199.58 -32663.2}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 304}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa09f
		{Position -4177.87 -32623}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 305}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa0a0
		{Position -4177.35 -32584.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 306}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa0a1
		{Position -4189.41 -32747.6}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 307}
		{FsmState "stand_noaim"}
	}
	{Human "" 0xa0a2
		{Position -2747.49 -32846.1}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 308}
		{FsmState "stand_noaim"}
	}
	{Link 0x813c {0x8141 "driver"}}
	{Link 0x813d {0x8141 "gunner"}}
	{Link 0x813e {0x8142 "driver"}}
	{Link 0x813f {0x8143 "driver"}}
	{Link 0x8140 {0x8143 "gunner"}}
	{Link 0x814f {0x814e "driver"}}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8001}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8002}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8003}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8004}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8005}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8006}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8007}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8008}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8009}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x800a}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x800b}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x800d}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x800e}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x800f}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8010}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8011}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8012}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8013}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8029}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x802a}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x802b}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x802c}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x802d}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x802e}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x802f}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8030}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8031}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8032}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8033}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8034}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8035}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8036}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8037}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8038}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8039}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x803a}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x803b}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8051}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8052}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8053}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8054}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8055}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8056}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8057}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8058}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8059}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x805a}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x805b}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x805c}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x805d}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x805e}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x805f}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8060}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8061}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8062}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8063}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8064}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8078}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8079}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x807a}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x807b}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x807c}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x807d}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x807e}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x807f}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0xc000}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0xc001}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0xc002}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0xc003}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0xc004}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0xc005}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0xc006}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0xc007}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0xc008}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0xc009}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0xc00a}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0xc00b}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x808a}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x808b}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x808c}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x808d}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x808e}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x808f}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8097}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8098}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8099}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x809c}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80b1}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80b2}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80b3}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80b4}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80b5}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80b6}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80b7}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80b8}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80b9}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80ba}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80bb}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80bc}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80bd}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80be}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80bf}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80c0}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80c1}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80c2}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80c3}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80d9}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80da}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80db}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80dc}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80dd}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80de}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80df}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80e0}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80e1}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80e2}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80e3}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80e4}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80e5}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80e6}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80e7}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80e8}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80e9}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80ea}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x80eb}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8101}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8103}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8104}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8105}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8106}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8107}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8108}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8109}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x810a}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x810b}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x810c}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x810d}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x810e}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x810f}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8110}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8111}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8112}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8113}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8129}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x812a}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x812b}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x812c}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x812d}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x812e}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x812f}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8130}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8131}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8132}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8133}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8134}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8135}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8136}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8137}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8138}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x8139}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x813a}
	{Tags "1_a_2-3" "1_b_2-3" "2_b_2-3" "3_b_2-3" "4_b_2-3" "5_b_2-3" "2_a_2-3" "3_a_2-3" "4_a_2-3" "5_a_2-3" "extra_inf_def" "random_def" "cmp_def" 0x813b}
	{Tags "engine_count_2" "move_fast" "hidden" "airstrike_ger" "air_vehicle" "no_scavenge" 0x8141}
	{Tags "engine_count_1" "move_fast" "hidden" "airstrike_rus" "air_vehicle" "no_scavenge" 0x8142}
	{Tags "engine_count_2" "move_fast" "hidden" "airstrike_fin" "air_vehicle" "no_scavenge" 0x8143}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0x814a}
	{Tags "engine_count_1" "move_fast" "hidden" "airstrike_usa" "air_vehicle" "no_scavenge" 0x814e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa000}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa001}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa002}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa003}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa004}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa005}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa006}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa007}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa008}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa009}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa00a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa00b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa00c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa00d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa00e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa00f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa010}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa011}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa012}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa013}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa014}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa015}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa016}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa017}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa018}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa019}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa01a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa01b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa01c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa01d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa01e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa01f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa020}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa021}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa022}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa023}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa024}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa025}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa026}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa027}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa028}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa029}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa02a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa02b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa02c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa02d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa02e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa02f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa030}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa031}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa032}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa033}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa034}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa035}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa036}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa037}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa038}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa039}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa03a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa03b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa03c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa03d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa03e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa03f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa040}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa041}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa042}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa043}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa044}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa045}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa046}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa047}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa048}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa049}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa04a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa04b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa04c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa04d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa04e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa04f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa050}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa051}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa052}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa053}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa054}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa055}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa056}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa057}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa058}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa059}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa05a}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa05b}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa05c}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa05d}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa05e}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa05f}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa060}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa061}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa062}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa063}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa064}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa065}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa066}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa067}
	{Tags "1_a_1-3" "1_b_1-3" "2_b_1-3" "3_b_1-3" "4_b_1-3" "5_b_1-3" "2_a_1-3" "3_a_1-3" "4_a_1-3" "5_a_1-3" "extra_inf_def" "random_def" "cmp_def" 0xa068}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa069}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa06a}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa06b}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa06c}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa06d}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa06e}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa06f}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa070}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa071}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa072}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa073}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa074}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa075}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa076}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa077}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa078}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa079}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa07a}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa07b}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa07c}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa07d}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa07e}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa07f}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa080}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa081}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa082}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa083}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa084}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa085}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa086}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa087}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa088}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa089}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa08a}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa08b}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa08c}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa08d}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa08e}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa08f}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa090}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa091}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa092}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa093}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa094}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa095}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa096}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa097}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa098}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa099}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa09a}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa09b}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa09c}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa09d}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa09e}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa09f}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa0a0}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa0a1}
	{Tags "1_a_3" "1_b_3" "2_b_3" "3_b_3" "4_b_3" "5_b_3" "2_a_3" "3_a_3" "4_a_3" "5_a_3" "extra_inf_def" "random_def" "cmp_def" 0xa0a2}
	{Inventory 0x8001
		{box
			{clear}
		}
	}
	{Inventory 0x8002
		{box
			{clear}
		}
	}
	{Inventory 0x8003
		{box
			{clear}
		}
	}
	{Inventory 0x8004
		{box
			{clear}
		}
	}
	{Inventory 0x8005
		{box
			{clear}
		}
	}
	{Inventory 0x8006
		{box
			{clear}
		}
	}
	{Inventory 0x8007
		{box
			{clear}
		}
	}
	{Inventory 0x8008
		{box
			{clear}
		}
	}
	{Inventory 0x8009
		{box
			{clear}
		}
	}
	{Inventory 0x800a
		{box
			{clear}
		}
	}
	{Inventory 0x800b
		{box
			{clear}
		}
	}
	{Inventory 0x800d
		{box
			{clear}
		}
	}
	{Inventory 0x800e
		{box
			{clear}
		}
	}
	{Inventory 0x800f
		{box
			{clear}
		}
	}
	{Inventory 0x8010
		{box
			{clear}
		}
	}
	{Inventory 0x8011
		{box
			{clear}
		}
	}
	{Inventory 0x8012
		{box
			{clear}
		}
	}
	{Inventory 0x8013
		{box
			{clear}
		}
	}
	{Inventory 0x8029
		{box
			{clear}
		}
	}
	{Inventory 0x802a
		{box
			{clear}
		}
	}
	{Inventory 0x802b
		{box
			{clear}
		}
	}
	{Inventory 0x802c
		{box
			{clear}
		}
	}
	{Inventory 0x802d
		{box
			{clear}
		}
	}
	{Inventory 0x802e
		{box
			{clear}
		}
	}
	{Inventory 0x802f
		{box
			{clear}
		}
	}
	{Inventory 0x8030
		{box
			{clear}
		}
	}
	{Inventory 0x8031
		{box
			{clear}
		}
	}
	{Inventory 0x8032
		{box
			{clear}
		}
	}
	{Inventory 0x8033
		{box
			{clear}
		}
	}
	{Inventory 0x8034
		{box
			{clear}
		}
	}
	{Inventory 0x8035
		{box
			{clear}
		}
	}
	{Inventory 0x8036
		{box
			{clear}
		}
	}
	{Inventory 0x8037
		{box
			{clear}
		}
	}
	{Inventory 0x8038
		{box
			{clear}
		}
	}
	{Inventory 0x8039
		{box
			{clear}
		}
	}
	{Inventory 0x803a
		{box
			{clear}
		}
	}
	{Inventory 0x803b
		{box
			{clear}
		}
	}
	{Inventory 0x8051
		{box
			{clear}
		}
	}
	{Inventory 0x8052
		{box
			{clear}
		}
	}
	{Inventory 0x8053
		{box
			{clear}
		}
	}
	{Inventory 0x8054
		{box
			{clear}
		}
	}
	{Inventory 0x8055
		{box
			{clear}
		}
	}
	{Inventory 0x8056
		{box
			{clear}
		}
	}
	{Inventory 0x8057
		{box
			{clear}
		}
	}
	{Inventory 0x8058
		{box
			{clear}
		}
	}
	{Inventory 0x8059
		{box
			{clear}
		}
	}
	{Inventory 0x805a
		{box
			{clear}
		}
	}
	{Inventory 0x805b
		{box
			{clear}
		}
	}
	{Inventory 0x805c
		{box
			{clear}
		}
	}
	{Inventory 0x805d
		{box
			{clear}
		}
	}
	{Inventory 0x805e
		{box
			{clear}
		}
	}
	{Inventory 0x805f
		{box
			{clear}
		}
	}
	{Inventory 0x8060
		{box
			{clear}
		}
	}
	{Inventory 0x8061
		{box
			{clear}
		}
	}
	{Inventory 0x8062
		{box
			{clear}
		}
	}
	{Inventory 0x8063
		{box
			{clear}
		}
	}
	{Inventory 0x8064
		{box
			{clear}
		}
	}
	{Inventory 0x8078
		{box
			{clear}
		}
	}
	{Inventory 0x8079
		{box
			{clear}
		}
	}
	{Inventory 0x807a
		{box
			{clear}
		}
	}
	{Inventory 0x807b
		{box
			{clear}
		}
	}
	{Inventory 0x807c
		{box
			{clear}
		}
	}
	{Inventory 0x807d
		{box
			{clear}
		}
	}
	{Inventory 0x807e
		{box
			{clear}
		}
	}
	{Inventory 0x807f
		{box
			{clear}
		}
	}
	{Inventory 0xc000
		{box
			{clear}
		}
	}
	{Inventory 0xc001
		{box
			{clear}
		}
	}
	{Inventory 0xc002
		{box
			{clear}
		}
	}
	{Inventory 0xc003
		{box
			{clear}
		}
	}
	{Inventory 0xc004
		{box
			{clear}
		}
	}
	{Inventory 0xc005
		{box
			{clear}
		}
	}
	{Inventory 0xc006
		{box
			{clear}
		}
	}
	{Inventory 0xc007
		{box
			{clear}
		}
	}
	{Inventory 0xc008
		{box
			{clear}
		}
	}
	{Inventory 0xc009
		{box
			{clear}
		}
	}
	{Inventory 0xc00a
		{box
			{clear}
		}
	}
	{Inventory 0xc00b
		{box
			{clear}
		}
	}
	{Inventory 0x808a
		{box
			{clear}
		}
	}
	{Inventory 0x808b
		{box
			{clear}
		}
	}
	{Inventory 0x808c
		{box
			{clear}
		}
	}
	{Inventory 0x808d
		{box
			{clear}
		}
	}
	{Inventory 0x808e
		{box
			{clear}
		}
	}
	{Inventory 0x808f
		{box
			{clear}
		}
	}
	{Inventory 0x8097
		{box
			{clear}
		}
	}
	{Inventory 0x8098
		{box
			{clear}
		}
	}
	{Inventory 0x8099
		{box
			{clear}
		}
	}
	{Inventory 0x809c
		{box
			{clear}
		}
	}
	{Inventory 0x80b1
		{box
			{clear}
		}
	}
	{Inventory 0x80b2
		{box
			{clear}
		}
	}
	{Inventory 0x80b3
		{box
			{clear}
		}
	}
	{Inventory 0x80b4
		{box
			{clear}
		}
	}
	{Inventory 0x80b5
		{box
			{clear}
		}
	}
	{Inventory 0x80b6
		{box
			{clear}
		}
	}
	{Inventory 0x80b7
		{box
			{clear}
		}
	}
	{Inventory 0x80b8
		{box
			{clear}
		}
	}
	{Inventory 0x80b9
		{box
			{clear}
		}
	}
	{Inventory 0x80ba
		{box
			{clear}
		}
	}
	{Inventory 0x80bb
		{box
			{clear}
		}
	}
	{Inventory 0x80bc
		{box
			{clear}
		}
	}
	{Inventory 0x80bd
		{box
			{clear}
		}
	}
	{Inventory 0x80be
		{box
			{clear}
		}
	}
	{Inventory 0x80bf
		{box
			{clear}
		}
	}
	{Inventory 0x80c0
		{box
			{clear}
		}
	}
	{Inventory 0x80c1
		{box
			{clear}
		}
	}
	{Inventory 0x80c2
		{box
			{clear}
		}
	}
	{Inventory 0x80c3
		{box
			{clear}
		}
	}
	{Inventory 0x80d9
		{box
			{clear}
		}
	}
	{Inventory 0x80da
		{box
			{clear}
		}
	}
	{Inventory 0x80db
		{box
			{clear}
		}
	}
	{Inventory 0x80dc
		{box
			{clear}
		}
	}
	{Inventory 0x80dd
		{box
			{clear}
		}
	}
	{Inventory 0x80de
		{box
			{clear}
		}
	}
	{Inventory 0x80df
		{box
			{clear}
		}
	}
	{Inventory 0x80e0
		{box
			{clear}
		}
	}
	{Inventory 0x80e1
		{box
			{clear}
		}
	}
	{Inventory 0x80e2
		{box
			{clear}
		}
	}
	{Inventory 0x80e3
		{box
			{clear}
		}
	}
	{Inventory 0x80e4
		{box
			{clear}
		}
	}
	{Inventory 0x80e5
		{box
			{clear}
		}
	}
	{Inventory 0x80e6
		{box
			{clear}
		}
	}
	{Inventory 0x80e7
		{box
			{clear}
		}
	}
	{Inventory 0x80e8
		{box
			{clear}
		}
	}
	{Inventory 0x80e9
		{box
			{clear}
		}
	}
	{Inventory 0x80ea
		{box
			{clear}
		}
	}
	{Inventory 0x80eb
		{box
			{clear}
		}
	}
	{Inventory 0x8101
		{box
			{clear}
		}
	}
	{Inventory 0x8103
		{box
			{clear}
		}
	}
	{Inventory 0x8104
		{box
			{clear}
		}
	}
	{Inventory 0x8105
		{box
			{clear}
		}
	}
	{Inventory 0x8106
		{box
			{clear}
		}
	}
	{Inventory 0x8107
		{box
			{clear}
		}
	}
	{Inventory 0x8108
		{box
			{clear}
		}
	}
	{Inventory 0x8109
		{box
			{clear}
		}
	}
	{Inventory 0x810a
		{box
			{clear}
		}
	}
	{Inventory 0x810b
		{box
			{clear}
		}
	}
	{Inventory 0x810c
		{box
			{clear}
		}
	}
	{Inventory 0x810d
		{box
			{clear}
		}
	}
	{Inventory 0x810e
		{box
			{clear}
		}
	}
	{Inventory 0x810f
		{box
			{clear}
		}
	}
	{Inventory 0x8110
		{box
			{clear}
		}
	}
	{Inventory 0x8111
		{box
			{clear}
		}
	}
	{Inventory 0x8112
		{box
			{clear}
		}
	}
	{Inventory 0x8113
		{box
			{clear}
		}
	}
	{Inventory 0x8129
		{box
			{clear}
		}
	}
	{Inventory 0x812a
		{box
			{clear}
		}
	}
	{Inventory 0x812b
		{box
			{clear}
		}
	}
	{Inventory 0x812c
		{box
			{clear}
		}
	}
	{Inventory 0x812d
		{box
			{clear}
		}
	}
	{Inventory 0x812e
		{box
			{clear}
		}
	}
	{Inventory 0x812f
		{box
			{clear}
		}
	}
	{Inventory 0x8130
		{box
			{clear}
		}
	}
	{Inventory 0x8131
		{box
			{clear}
		}
	}
	{Inventory 0x8132
		{box
			{clear}
		}
	}
	{Inventory 0x8133
		{box
			{clear}
		}
	}
	{Inventory 0x8134
		{box
			{clear}
		}
	}
	{Inventory 0x8135
		{box
			{clear}
		}
	}
	{Inventory 0x8136
		{box
			{clear}
		}
	}
	{Inventory 0x8137
		{box
			{clear}
		}
	}
	{Inventory 0x8138
		{box
			{clear}
		}
	}
	{Inventory 0x8139
		{box
			{clear}
		}
	}
	{Inventory 0x813a
		{box
			{clear}
		}
	}
	{Inventory 0x813b
		{box
			{clear}
		}
	}
	{Inventory 0x813c
		{box
			{clear}
			{item "luger" filled {cell 0 0}}
			{item "pistol" "ammo" 28 {cell 3 0}}
			{item "bandage_ger" {cell 5 0}}
			{item "ger_m43_cap_luftwaffe" {cell 0 1}{user "head"}}
		}
	}
	{Inventory 0x813d
		{box
			{clear}
			{item "luger" filled {cell 0 0}}
			{item "pistol" "ammo" 28 {cell 3 0}}
			{item "bandage_ger" {cell 5 0}}
			{item "ger_m43_cap_luftwaffe" {cell 0 1}{user "head"}}
		}
	}
	{Inventory 0x813e
		{box
			{clear}
			{item "tt33" filled {cell 0 0}}
			{item "tt33" "ammo" 8 {cell 2 0}}
			{item "tt33" "ammo" 4 {cell 3 0}}
			{item "bandage_rus" {cell 4 0}}
			{item "soviet_tankovy_helmet" {cell 6 0}{user "head"}}
		}
	}
	{Inventory 0x813f
		{box
			{clear}
			{item "lahti_l35" filled {cell 0 0}}
			{item "pistol" "ammo" 16 {cell 2 0}}
			{item "bandage_fin" {cell 4 0}}
			{item "bandage_fin" {cell 6 0}}
			{item "fin_tank_helmet" {cell 0 1}{user "head"}}
		}
	}
	{Inventory 0x8140
		{box
			{clear}
			{item "lahti_l35" filled {cell 0 0}}
			{item "pistol" "ammo" 16 {cell 2 0}}
			{item "bandage_fin" {cell 4 0}}
			{item "bandage_fin" {cell 6 0}}
			{item "bandage_fin" {cell 0 1}}
			{item "fin_tank_helmet" {cell 2 1}{user "head"}}
		}
	}
	{Inventory 0x814a
		{box
			{clear}
		}
	}
	{Inventory 0x814f
		{box
			{clear}
			{item "m1911" filled {cell 0 0}}
			{item "m1911_mag" "ammo" 7 {cell 2 0}}
			{item "m1911_mag" "ammo" 7 {cell 3 0}}
			{item "m1911_mag" "ammo" 7 {cell 4 0}}
			{item "m1911_mag" "ammo" 7 {cell 5 0}}
			{item "bandage_usa" {cell 6 0}}
			{item "us_m1_b" {cell 0 1}{user "head"}}
		}
	}
	{Inventory 0xa000
		{box
			{clear}
		}
	}
	{Inventory 0xa001
		{box
			{clear}
		}
	}
	{Inventory 0xa002
		{box
			{clear}
		}
	}
	{Inventory 0xa003
		{box
			{clear}
		}
	}
	{Inventory 0xa004
		{box
			{clear}
		}
	}
	{Inventory 0xa005
		{box
			{clear}
		}
	}
	{Inventory 0xa006
		{box
			{clear}
		}
	}
	{Inventory 0xa007
		{box
			{clear}
		}
	}
	{Inventory 0xa008
		{box
			{clear}
		}
	}
	{Inventory 0xa009
		{box
			{clear}
		}
	}
	{Inventory 0xa00a
		{box
			{clear}
		}
	}
	{Inventory 0xa00b
		{box
			{clear}
		}
	}
	{Inventory 0xa00c
		{box
			{clear}
		}
	}
	{Inventory 0xa00d
		{box
			{clear}
		}
	}
	{Inventory 0xa00e
		{box
			{clear}
		}
	}
	{Inventory 0xa00f
		{box
			{clear}
		}
	}
	{Inventory 0xa010
		{box
			{clear}
		}
	}
	{Inventory 0xa011
		{box
			{clear}
		}
	}
	{Inventory 0xa012
		{box
			{clear}
		}
	}
	{Inventory 0xa013
		{box
			{clear}
		}
	}
	{Inventory 0xa014
		{box
			{clear}
		}
	}
	{Inventory 0xa015
		{box
			{clear}
		}
	}
	{Inventory 0xa016
		{box
			{clear}
		}
	}
	{Inventory 0xa017
		{box
			{clear}
		}
	}
	{Inventory 0xa018
		{box
			{clear}
		}
	}
	{Inventory 0xa019
		{box
			{clear}
		}
	}
	{Inventory 0xa01a
		{box
			{clear}
		}
	}
	{Inventory 0xa01b
		{box
			{clear}
		}
	}
	{Inventory 0xa01c
		{box
			{clear}
		}
	}
	{Inventory 0xa01d
		{box
			{clear}
		}
	}
	{Inventory 0xa01e
		{box
			{clear}
		}
	}
	{Inventory 0xa01f
		{box
			{clear}
		}
	}
	{Inventory 0xa020
		{box
			{clear}
		}
	}
	{Inventory 0xa021
		{box
			{clear}
		}
	}
	{Inventory 0xa022
		{box
			{clear}
		}
	}
	{Inventory 0xa023
		{box
			{clear}
		}
	}
	{Inventory 0xa024
		{box
			{clear}
		}
	}
	{Inventory 0xa025
		{box
			{clear}
		}
	}
	{Inventory 0xa026
		{box
			{clear}
		}
	}
	{Inventory 0xa027
		{box
			{clear}
		}
	}
	{Inventory 0xa028
		{box
			{clear}
		}
	}
	{Inventory 0xa029
		{box
			{clear}
		}
	}
	{Inventory 0xa02a
		{box
			{clear}
		}
	}
	{Inventory 0xa02b
		{box
			{clear}
		}
	}
	{Inventory 0xa02c
		{box
			{clear}
		}
	}
	{Inventory 0xa02d
		{box
			{clear}
		}
	}
	{Inventory 0xa02e
		{box
			{clear}
		}
	}
	{Inventory 0xa02f
		{box
			{clear}
		}
	}
	{Inventory 0xa030
		{box
			{clear}
		}
	}
	{Inventory 0xa031
		{box
			{clear}
		}
	}
	{Inventory 0xa032
		{box
			{clear}
		}
	}
	{Inventory 0xa033
		{box
			{clear}
		}
	}
	{Inventory 0xa034
		{box
			{clear}
		}
	}
	{Inventory 0xa035
		{box
			{clear}
		}
	}
	{Inventory 0xa036
		{box
			{clear}
		}
	}
	{Inventory 0xa037
		{box
			{clear}
		}
	}
	{Inventory 0xa038
		{box
			{clear}
		}
	}
	{Inventory 0xa039
		{box
			{clear}
		}
	}
	{Inventory 0xa03a
		{box
			{clear}
		}
	}
	{Inventory 0xa03b
		{box
			{clear}
		}
	}
	{Inventory 0xa03c
		{box
			{clear}
		}
	}
	{Inventory 0xa03d
		{box
			{clear}
		}
	}
	{Inventory 0xa03e
		{box
			{clear}
		}
	}
	{Inventory 0xa03f
		{box
			{clear}
		}
	}
	{Inventory 0xa040
		{box
			{clear}
		}
	}
	{Inventory 0xa041
		{box
			{clear}
		}
	}
	{Inventory 0xa042
		{box
			{clear}
		}
	}
	{Inventory 0xa043
		{box
			{clear}
		}
	}
	{Inventory 0xa044
		{box
			{clear}
		}
	}
	{Inventory 0xa045
		{box
			{clear}
		}
	}
	{Inventory 0xa046
		{box
			{clear}
		}
	}
	{Inventory 0xa047
		{box
			{clear}
		}
	}
	{Inventory 0xa048
		{box
			{clear}
		}
	}
	{Inventory 0xa049
		{box
			{clear}
		}
	}
	{Inventory 0xa04a
		{box
			{clear}
		}
	}
	{Inventory 0xa04b
		{box
			{clear}
		}
	}
	{Inventory 0xa04c
		{box
			{clear}
		}
	}
	{Inventory 0xa04d
		{box
			{clear}
		}
	}
	{Inventory 0xa04e
		{box
			{clear}
		}
	}
	{Inventory 0xa04f
		{box
			{clear}
		}
	}
	{Inventory 0xa050
		{box
			{clear}
		}
	}
	{Inventory 0xa051
		{box
			{clear}
		}
	}
	{Inventory 0xa052
		{box
			{clear}
		}
	}
	{Inventory 0xa053
		{box
			{clear}
		}
	}
	{Inventory 0xa054
		{box
			{clear}
		}
	}
	{Inventory 0xa055
		{box
			{clear}
		}
	}
	{Inventory 0xa056
		{box
			{clear}
		}
	}
	{Inventory 0xa057
		{box
			{clear}
		}
	}
	{Inventory 0xa058
		{box
			{clear}
		}
	}
	{Inventory 0xa059
		{box
			{clear}
		}
	}
	{Inventory 0xa05a
		{box
			{clear}
		}
	}
	{Inventory 0xa05b
		{box
			{clear}
		}
	}
	{Inventory 0xa05c
		{box
			{clear}
		}
	}
	{Inventory 0xa05d
		{box
			{clear}
		}
	}
	{Inventory 0xa05e
		{box
			{clear}
		}
	}
	{Inventory 0xa05f
		{box
			{clear}
		}
	}
	{Inventory 0xa060
		{box
			{clear}
		}
	}
	{Inventory 0xa061
		{box
			{clear}
		}
	}
	{Inventory 0xa062
		{box
			{clear}
		}
	}
	{Inventory 0xa063
		{box
			{clear}
		}
	}
	{Inventory 0xa064
		{box
			{clear}
		}
	}
	{Inventory 0xa065
		{box
			{clear}
		}
	}
	{Inventory 0xa066
		{box
			{clear}
		}
	}
	{Inventory 0xa067
		{box
			{clear}
		}
	}
	{Inventory 0xa068
		{box
			{clear}
		}
	}
	{Inventory 0xa069
		{box
			{clear}
		}
	}
	{Inventory 0xa06a
		{box
			{clear}
		}
	}
	{Inventory 0xa06b
		{box
			{clear}
		}
	}
	{Inventory 0xa06c
		{box
			{clear}
		}
	}
	{Inventory 0xa06d
		{box
			{clear}
		}
	}
	{Inventory 0xa06e
		{box
			{clear}
		}
	}
	{Inventory 0xa06f
		{box
			{clear}
		}
	}
	{Inventory 0xa070
		{box
			{clear}
		}
	}
	{Inventory 0xa071
		{box
			{clear}
		}
	}
	{Inventory 0xa072
		{box
			{clear}
		}
	}
	{Inventory 0xa073
		{box
			{clear}
		}
	}
	{Inventory 0xa074
		{box
			{clear}
		}
	}
	{Inventory 0xa075
		{box
			{clear}
		}
	}
	{Inventory 0xa076
		{box
			{clear}
		}
	}
	{Inventory 0xa077
		{box
			{clear}
		}
	}
	{Inventory 0xa078
		{box
			{clear}
		}
	}
	{Inventory 0xa079
		{box
			{clear}
		}
	}
	{Inventory 0xa07a
		{box
			{clear}
		}
	}
	{Inventory 0xa07b
		{box
			{clear}
		}
	}
	{Inventory 0xa07c
		{box
			{clear}
		}
	}
	{Inventory 0xa07d
		{box
			{clear}
		}
	}
	{Inventory 0xa07e
		{box
			{clear}
		}
	}
	{Inventory 0xa07f
		{box
			{clear}
		}
	}
	{Inventory 0xa080
		{box
			{clear}
		}
	}
	{Inventory 0xa081
		{box
			{clear}
		}
	}
	{Inventory 0xa082
		{box
			{clear}
		}
	}
	{Inventory 0xa083
		{box
			{clear}
		}
	}
	{Inventory 0xa084
		{box
			{clear}
		}
	}
	{Inventory 0xa085
		{box
			{clear}
		}
	}
	{Inventory 0xa086
		{box
			{clear}
		}
	}
	{Inventory 0xa087
		{box
			{clear}
		}
	}
	{Inventory 0xa088
		{box
			{clear}
		}
	}
	{Inventory 0xa089
		{box
			{clear}
		}
	}
	{Inventory 0xa08a
		{box
			{clear}
		}
	}
	{Inventory 0xa08b
		{box
			{clear}
		}
	}
	{Inventory 0xa08c
		{box
			{clear}
		}
	}
	{Inventory 0xa08d
		{box
			{clear}
		}
	}
	{Inventory 0xa08e
		{box
			{clear}
		}
	}
	{Inventory 0xa08f
		{box
			{clear}
		}
	}
	{Inventory 0xa090
		{box
			{clear}
		}
	}
	{Inventory 0xa091
		{box
			{clear}
		}
	}
	{Inventory 0xa092
		{box
			{clear}
		}
	}
	{Inventory 0xa093
		{box
			{clear}
		}
	}
	{Inventory 0xa094
		{box
			{clear}
		}
	}
	{Inventory 0xa095
		{box
			{clear}
		}
	}
	{Inventory 0xa096
		{box
			{clear}
		}
	}
	{Inventory 0xa097
		{box
			{clear}
		}
	}
	{Inventory 0xa098
		{box
			{clear}
		}
	}
	{Inventory 0xa099
		{box
			{clear}
		}
	}
	{Inventory 0xa09a
		{box
			{clear}
		}
	}
	{Inventory 0xa09b
		{box
			{clear}
		}
	}
	{Inventory 0xa09c
		{box
			{clear}
		}
	}
	{Inventory 0xa09d
		{box
			{clear}
		}
	}
	{Inventory 0xa09e
		{box
			{clear}
		}
	}
	{Inventory 0xa09f
		{box
			{clear}
		}
	}
	{Inventory 0xa0a0
		{box
			{clear}
		}
	}
	{Inventory 0xa0a1
		{box
			{clear}
		}
	}
	{Inventory 0xa0a2
		{box
			{clear}
		}
	}
	{Brain 0x8001
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8002
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8003
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8004
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8005
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8006
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8007
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8008
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8009
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x800a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x800b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x800d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x800e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x800f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8010
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8011
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8012
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8013
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8029
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x802a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x802b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x802c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x802d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x802e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x802f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8030
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8031
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8032
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8033
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8034
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8035
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8036
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8037
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8038
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8039
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x803a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x803b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8051
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8052
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8053
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8054
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8055
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8056
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8057
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8058
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8059
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x805a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x805b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x805c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x805d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x805e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x805f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8060
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8061
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8062
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8063
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8064
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8078
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8079
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x807a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x807b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x807c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x807d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x807e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x807f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc000
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc001
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc002
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc003
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc004
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc005
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc006
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc007
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc008
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc009
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc00a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xc00b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x808a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x808b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x808c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x808d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x808e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x808f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8097
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8098
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8099
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x809c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80b1
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80b2
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80b3
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80b4
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80b5
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80b6
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80b7
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80b8
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80b9
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80ba
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80bb
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80bc
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80bd
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80be
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80bf
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80c0
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80c1
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80c2
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80c3
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80d9
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80da
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80db
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80dc
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80dd
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80de
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80df
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80e0
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80e1
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80e2
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80e3
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80e4
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80e5
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80e6
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80e7
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80e8
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80e9
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80ea
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x80eb
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8101
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8103
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8104
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8105
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8106
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8107
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8108
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8109
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x810a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x810b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x810c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x810d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x810e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x810f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8110
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8111
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8112
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8113
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8129
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x812a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x812b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x812c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x812d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x812e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x812f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8130
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8131
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8132
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8133
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8134
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8135
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8136
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8137
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8138
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8139
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x813a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x813b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x813c
		{Properties
			{advance_ratio 8}
			{retreat_ratio 99}
		}
	}
	{Brain 0x813d
		{Properties
			{advance_ratio 8}
			{retreat_ratio 99}
		}
	}
	{Brain 0x813e
		{Properties
			{move_mode hold}
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x813f
		{Properties
			{move_mode hold}
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8140
		{Properties
			{move_mode hold}
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x8141
		{Properties
			{fire_mode hold}
		}
	}
	{Brain 0x8142
		{Properties
			{fire_mode hold}
		}
	}
	{Brain 0x8143
		{Properties
			{fire_mode hold}
		}
	}
	{Brain 0x814a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0x814e
		{Properties
			{fire_mode hold}
		}
	}
	{Brain 0x814f
		{Properties
			{advance_ratio 8}
			{retreat_ratio 99}
		}
	}
	{Brain 0xa000
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa001
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa002
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa003
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa004
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa005
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa006
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa007
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa008
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa009
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa00a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa00b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa00c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa00d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa00e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa00f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa010
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa011
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa012
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa013
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa014
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa015
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa016
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa017
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa018
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa019
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa01a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa01b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa01c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa01d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa01e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa01f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa020
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa021
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa022
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa023
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa024
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa025
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa026
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa027
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa028
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa029
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa02a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa02b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa02c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa02d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa02e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa02f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa030
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa031
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa032
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa033
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa034
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa035
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa036
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa037
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa038
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa039
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa03a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa03b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa03c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa03d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa03e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa03f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa040
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa041
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa042
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa043
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa044
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa045
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa046
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa047
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa048
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa049
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa04a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa04b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa04c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa04d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa04e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa04f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa050
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa051
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa052
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa053
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa054
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa055
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa056
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa057
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa058
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa059
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa05a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa05b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa05c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa05d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa05e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa05f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa060
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa061
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa062
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa063
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa064
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa065
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa066
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa067
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa068
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa069
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa06a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa06b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa06c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa06d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa06e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa06f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa070
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa071
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa072
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa073
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa074
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa075
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa076
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa077
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa078
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa079
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa07a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa07b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa07c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa07d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa07e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa07f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa080
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa081
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa082
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa083
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa084
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa085
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa086
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa087
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa088
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa089
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa08a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa08b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa08c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa08d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa08e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa08f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa090
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa091
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa092
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa093
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa094
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa095
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa096
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa097
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa098
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa099
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa09a
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa09b
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa09c
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa09d
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa09e
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa09f
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa0a0
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa0a1
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}
	{Brain 0xa0a2
		{Properties
			{advance_ratio 0.5}
			{retreat_ratio 4}
		}
	}