{difficulty
	(include "difficulty_generic.inc")
	{any	;// temp to give enemy stats
		{health 0.33}
		{accuracy 0.33}
		{grenade_timeout 1.5}		; modifier on FiringTimeout
	}
	{enemy	;// not working in coop
		{health 0.33}
		{accuracy 0.33}
		{grenade_timeout 1.5}		; modifier on FiringTimeout
	}
	{ally
		{health 1.50}
		{accuracy 1.0}
		{grenade_timeout 0.50}
	}
	{player
		{health 2.00}
		{accuracy 1.0}
		{grenade_timeout 0.50}
	}

}